// Date: 2015/3/28 18:12:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.cfyifei.gui.blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPDG extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;

    public ModelPDG() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 8, 1, 8);
        Shape1.setRotationPoint(-4F, 23F, -2F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 32, 0);
        Shape2.addBox(0F, 0F, 0F, 10, 1, 1);
        Shape2.setRotationPoint(-5F, 22F, 6F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 32, 0);
        Shape5.addBox(0F, 0F, 0F, 10, 1, 1);
        Shape5.setRotationPoint(-5F, 22F, -3F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 9);
        Shape3.addBox(0F, 0F, 0F, 1, 1, 10);
        Shape3.setRotationPoint(4F, 22F, -3F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 0, 9);
        Shape6.addBox(0F, 0F, 0F, 1, 1, 10);
        Shape6.setRotationPoint(-5F, 22F, -3F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 32, 2);
        Shape4.addBox(0F, 0F, 0F, 1, 1, 6);
        Shape4.setRotationPoint(-0.5F, 22F, -9F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape5.render(f5);
        Shape3.render(f5);
        Shape6.render(f5);
        Shape4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
/*  public void setRotationAngle(int Angles)
  {
	if(Angles < 180){
		Angles = -180 + (Angles - 180);
	}
	Shape1.rotateAngleY = Angles/180F*3.14159265F;
	Shape2.rotateAngleY = Angles/180F*3.14159265F;
	Shape3.rotateAngleY = Angles/180F*3.14159265F;
	Shape4.rotateAngleY = Angles/180F*3.14159265F;
	Shape5.rotateAngleY = Angles/180F*3.14159265F;
	Shape6.rotateAngleY = Angles/180F*3.14159265F;
  }*/
}
