package com.foodcraft.init;

import com.foodcraft.FoodCraft;
import com.foodcraft.item.FcFood;
import com.foodcraft.item.ItemCakeFoodcraft;
import com.foodcraft.item.ItemCleaningBucket;
import com.foodcraft.item.ItemCookie;
import com.foodcraft.item.ItemDrink;
import com.foodcraft.item.ItemFc;
import com.foodcraft.item.ItemFoodChili;
import com.foodcraft.item.ItemGoldenAppleWine;
import com.foodcraft.item.ItemGoldenGrapeWine;
import com.foodcraft.item.ItemJam;
import com.foodcraft.item.ItemKitchenKnifeDiamond;
import com.foodcraft.item.ItemKitchenKnifeEmerald;
import com.foodcraft.item.ItemKitchenKnifeGold;
import com.foodcraft.item.ItemStapleFood;
import com.foodcraft.item.ItemTest;
import com.foodcraft.item.ItemWine;
import com.foodcraft.item.ItemWrench;
import com.foodcraft.plant.items.*;

import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelBakery;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemReed;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.PotionHelper;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;

public class FoodcraftItems{

	static public Item ItemScallion,ItemZongye,ItemPorridge,ItemEggSoup,ItemIronSheet,ItemKitchenKnife,ItemRice,ItemMilledRice,ItemFlour,ItemPeanut,
	ItemBeans,ItemPeanutOil,ItemSoybeanMilk,ItemMachineCore,ItemPoachedEgg,ItemPancakes,ItemDumplingWrappers,ItemDumplingMeat,ItemDumpling,ItemFriedDumpling,
	ItemChocolate,ItemChocolateDust,ItemVegetable,ItemTomato,ItemChili,ItemFlourSilk,ItemEggplant,ItemGrapes,ItemSalt,Itemwater,ItemTofu,
	ItemSoySauce,ItemStickyRice, ItemDriedTofu,ItemCookedRice,ItemFanqiechaojidanfan,ItemDisanxian,ItemVinegar,ItemYuxiangrousi,ItemGongbaojiding,
    ItemDrumstick,ItemPotatoChips,ItemPotatoesWire,ItemChaotudousifan,ItemFriedPotatoChips,ItemDuojiaoyutou,ItemWatercress,ItemMapodoufufan,
	ItemStarches,ItemHongshaoroufan,ItemHuiguoroufan,ItemMogudunjitang,ItemStickyRiceDumpling,ItemStickyRiceFlour,ItemTangyuan,
	ItemPeanutTangyuanStuffing,ItemStickyRiceDough,ItemDoughTwist,ItemNewYearCake,ItemSpringRolls,ItemFriedChicken,ItemFrenchFries,ItemOrleansWing,ItemPopcornChicken,
	ItemAeljichifan,ItemOriginalRecipe,ItemFriedTofu,ItemFriedNewYearCake,ItemChips,ItemFriedBread,ItemFriedSpringRolls,ItemFriedDoughTwist,
	ItemFriedDrumstick,ItemBigChicken,ItemMediumChicken,ItemSmallChicken,ItemChickenWing,ItemTofuStrip,ItemCarrotStrip,ItemRedWine,ItemSpirit,ItemCider,
	ItemGrapeWine,ItemGoldenGrapeWine, ItemGoldenCider,ItemGoldenGrape,ItemChocolatesWater,ItemChocolatesMilk,ItemCarrotJuice,ItemGrapeJuice,
	ItemAppleJuice,ItemVegetableJuice,ItemGoldenGrapeJuice,ItemGoldenAppleJuice,ItemSoyMilk,ItemCoke,ItemSprite,ItemMelonJuice,ItemChocolatesmilk_ice,
	ItemGrapeJuice_ice,ItemAppleJuice_ice,ItemGoldenGrapeJuice_ice,ItemGoldenAppleJuice_ice,ItemMelonJuice_ice,ItemTea,ItemMilkTea,ItemCoffee,
	ItemBaiqiuji,ItemCongyouji,ItemKoushuiji,ItemLaziji,ItemQingzhenyu,ItemMalayu,ItemSuancaiyu,ItemKelejichifan,ItemBlockCurry,
	ItemGalijiroufan,ItemShuizhuniurou,ItemNoodles,ItemCrossingBridgeNoodles,ItemPasta,ItemPastaPork,ItemPastaBeef,ItemPastaChicken,
	ItemPreservedEggPorridge,ItemMooncake,ItemSteamedBuns,ItemSauerkrautCake,ItemYoutiao,ItemChiliTofuStrip,ItemWalnutShortbread,ItemAici,ItemStickyRiceCake,ItemChangfen,
	ItemSausage,ItemHotDog,ItemChineseSausage,ItemChineseBacon,ItemFriedSausage,ItemRibendoufu,ItemLaBaPorridge,ItemSmokedMaterial,ItemCheese,
	ItemPizza,ItemHamburger,ItemFoodcraftBucket,ItemNull,ItemSquidMeat,ItemCookedSquidMeat,ItemSquidSlices,ItemShucaizhong,ItemLajiaozhong,ItemFanqiezhong,
	ItemPutaozhong,ItemQiezizhong,ItemBailuobo,ItemQingjiao,ItemQingjiaozhong,ItemHongdou,ItemLvdou,ItemHongshu,ItemKaohongshu,ItemDoujiao,ItemWrench,
	ItemHuanggua,ItemHuangguazhong,ItemYumizhong,ItemYumi,ItemBailuobosi,ItemBailuobozhi,ItemFanqiezhi,ItemYumizhi,ItemHuangguazhi,ItemDousha,ItemKaoyumi,
	ItemBaoyumihua,ItemLi,ItemLizhi,ItemTaozi,ItemJuzi,ItemPipa,ItemMangguo,ItemNingmeng,ItemYouzi,ItemShizi,ItemMugua,ItemShanzha,ItemLongyan,ItemShiliu,
	ItemCaomei,ItemHongzao,ItemYezi,ItemYingtao,ItemXiangjiao,ItemJinkela,ItemLizizhi,ItemLizhizhi,ItemTaozizhi,ItemJuzizhi,ItemPipazhi,
	ItemMangguozhi,ItemNingmengzhi,ItemYouzizhi,ItemShizizhi,ItemMuguazhi,ItemShanzhazhi,ItemShiliuzhi,ItemHongzaozhi,ItemCaomeizhi,
	ItemYezizhi,ItemYingtaozhi,ItemXiangjiaozhi,ItemYenai,ItemLizhizhiice,ItemTaozizhiice,ItemJuzizhiice,ItemMangguozhiice,
	ItemNingmengzhiice,ItemMuguazhiice,ItemCaomeizhiice,ItemYezizhiice,ItemXiangjiaozhiice,ItemLizijiu,ItemLizhijiu,
	ItemTaozijiu,ItemMangguojiu,ItemNingmengjiu,ItemShiliujiu,ItemGuojiang,ItemBinggan,ItemDangao,
	ItemCaidaoHJ,ItemCaidaoZS,ItemCaidaoLBS,ItemBingganF,ItemBingganXN,ItemTest,ItemShaojiaodeshiwu;
	
	public static void init() {
		ItemIronSheet = new ItemFc("ItemIronSheet").setCreativeTab(FoodCraft.FcTabMachine);
		Itemwater = new ItemFc("Itemwater").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemNull = new ItemFc("ItemNull");			
		ItemMilledRice = new ItemFc("ItemMilledRice").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemFlour = new ItemFc("ItemFlour").setCreativeTab(FoodCraft.FcTabIngredient);		
		ItemPeanutOil = new ItemFc("ItemPeanutOil").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemMachineCore = new ItemFc("ItemMachineCore").setCreativeTab(FoodCraft.FcTabMachine);
		ItemDumplingWrappers = new ItemFc("ItemDumplingWrappers").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemDumplingMeat = new ItemFc("ItemDumplingMeat").setCreativeTab(FoodCraft.FcTabIngredient);		
		ItemChocolateDust = new ItemFc("ItemChocolateDust").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemSalt = new ItemFc("ItemSalt").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemSoySauce = new ItemFc("ItemSoySauce").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemVinegar = new ItemFc("ItemVinegar").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemPotatoChips = new ItemFc("ItemPotatoChips").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemPotatoesWire = new ItemFc("ItemPotatoesWire").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemWatercress = new ItemFc("ItemWatercress").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemStarches = new ItemFc("ItemStarches").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemZongye = new ItemFc("ItemZongye").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemStickyRiceFlour = new ItemFc("ItemStickyRiceFlour").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemStickyRiceDough = new ItemFc("ItemStickyRiceDough").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemPeanutTangyuanStuffing = new ItemFc("ItemPeanutTangyuanStuffing").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemBigChicken = new ItemFc("ItemBigChicken").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemMediumChicken = new ItemFc("ItemMediumChicken").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemSmallChicken = new ItemFc("ItemSmallChicken").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemTofuStrip = new ItemFc("ItemTofuStrip").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemCarrotStrip = new ItemFc("ItemCarrotStrip").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemFlourSilk = new ItemFc("ItemFlourSilk").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemSmokedMaterial = new ItemFc("ItemSmokedMaterial").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemBailuobosi = new ItemFc("ItemBailuobosi").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemDousha = new ItemFc("ItemDousha").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemJinkela = new ItemFc("ItemJinkela").setCreativeTab(FoodCraft.FcTabMachine);
		ItemShaojiaodeshiwu = new ItemFc("ItemShaojiaodeshiwu").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemRice = new ItemPlant(FoodcraftPlants.BlockShuidao, "ItemRice");			
		ItemPeanut = new ItemPlant(FoodcraftPlants.BlockHuashen, "ItemPeanut");				
		ItemShucaizhong = new ItemPlant(FoodcraftPlants.BlockShucai, "ItemShucaizhong");				
		ItemBeans = new ItemPlant(FoodcraftPlants.BlockDouzi, "ItemBeans");
		ItemLajiaozhong = new ItemPlant(FoodcraftPlants.BlockLajiao, "ItemLajiaozhong");
		ItemFanqiezhong = new ItemPlant(FoodcraftPlants.BlockFanqie, "ItemFanqiezhong");
		ItemPutaozhong = new ItemPlant(FoodcraftPlants.BlockPutao, "ItemPutaozhong");
		ItemQiezizhong = new ItemPlant(FoodcraftPlants.BlockQiezi, "ItemQiezizhong");
		ItemQingjiaozhong = new ItemPlant(FoodcraftPlants.BlockQingjiao, "ItemQingjiaozhong");
		ItemHongdou = new ItemPlant(FoodcraftPlants.BlockHongdou, "ItemHongdou");
		ItemLvdou = new ItemPlant(FoodcraftPlants.BlockLvdou,"ItemLvdou");
		ItemYumizhong = new ItemPlant(FoodcraftPlants.BlockYumi,"ItemYumizhong");
		ItemHuangguazhong = new ItemPlant(FoodcraftPlants.BlockHuanggua, "ItemHuangguazhong");
		ItemStickyRice = new ItemPlant(FoodcraftPlants.BlockNuodao, "ItemStickyRice");
		ItemCaomei = new ItemSweetPotato(FoodcraftPlants.BlockCaomei,3,"ItemCaomei");
		ItemBailuobo = new ItemSweetPotato(FoodcraftPlants.BlockBailuobo,3,"ItemBailuobo");
		ItemHongshu = new ItemSweetPotato(FoodcraftPlants.BlockHongshu,3,"ItemHongshu");
		ItemPoachedEgg = new FcFood(3, 5F, "ItemPoachedEgg").setCreativeTab(FoodCraft.FcTabSnack);
		ItemPancakes = new FcFood(3, 5F, "ItemPancakes").setCreativeTab(FoodCraft.FcTabSnack);
		ItemDumpling = new FcFood(3, 8F, "ItemDumpling").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedDumpling = new FcFood(3, 10F, "ItemFriedDumpling").setCreativeTab(FoodCraft.FcTabSnack);
		ItemChocolate = new FcFood(3, 4F, "ItemChocolate").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemTofu = new FcFood(3, 4F, "ItemTofu").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemDriedTofu = new FcFood(3, 6F, "ItemDriedTofu").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemCookedRice = new FcFood(3, 3F, "ItemCookedRice").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemFriedPotatoChips = new FcFood(3, 7F, "ItemFriedPotatoChips").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemPorridge = new FcFood(3, 7F, "ItemPorridge").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemEggSoup = new FcFood(3, 8F, "ItemEggSoup").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemMogudunjitang = new FcFood(3, 8F, "ItemMogudunjitang").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemStickyRiceDumpling = new FcFood(3, 8F, "ItemStickyRiceDumpling").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemDrumstick = new FcFood(3, 3F, "ItemDrumstick").setCreativeTab(FoodCraft.FcTabIngredient);
		ItemTangyuan = new FcFood(3, 8F, "ItemTangyuan").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedChicken = new FcFood(3, 6F, "ItemFriedChicken").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFrenchFries = new FcFood(3, 7F, "ItemFrenchFries").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemOrleansWing = new FcFood(3, 8F, "ItemOrleansWing").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemPopcornChicken = new FcFood(3, 4F, "ItemPopcornChicken").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemOriginalRecipe = new FcFood(3, 8F, "ItemOriginalRecipe").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemDoughTwist = new FcFood(3, 7F, "ItemDoughTwist").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemNewYearCake = new FcFood(3, 8F, "ItemNewYearCake").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemSpringRolls = new FcFood(3, 8F, "ItemSpringRolls").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedTofu = new FcFood(3, 6F, "ItemFriedTofu").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedNewYearCake = new FcFood(3, 10F, "ItemFriedNewYearCake").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChips = new FcFood(3, 7F, "ItemChips").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedBread = new FcFood(3, 7F, "ItemFriedBread").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedSpringRolls = new FcFood(3, 10F, "ItemFriedSpringRolls").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedDoughTwist = new FcFood(3, 10F, "ItemFriedDoughTwist").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedDrumstick = new FcFood(3, 5F, "ItemFriedDrumstick").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChickenWing = new FcFood(3, 4F, "ItemChickenWing").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemGoldenGrape = new FcFood(3, 20F, "ItemGoldenGrape" ,true).setCreativeTab(FoodCraft.FcTabPlant);
		ItemBlockCurry = new FcFood(3, 3F, "ItemBlockCurry").setCreativeTab(FoodCraft.FcTabIngredient);	
		ItemNoodles = new FcFood(3, 7F, "ItemNoodles").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemCrossingBridgeNoodles = new FcFood(3, 7F, "ItemCrossingBridgeNoodles").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemPasta = new FcFood(3, 7F, "ItemPasta").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemPreservedEggPorridge = new FcFood(3, 7F, "ItemPreservedEggPorridge").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemMooncake = new FcFood(3, 8F, "ItemMooncake").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemSteamedBuns = new FcFood(3, 4F, "ItemSteamedBuns").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemSauerkrautCake = new FcFood(3, 7F, "ItemSauerkrautCake").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemYoutiao = new FcFood(3, 8F, "ItemYoutiao").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChiliTofuStrip = new FcFood(3, 4F, "ItemChiliTofuStrip").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemWalnutShortbread = new FcFood(3, 8F, "ItemWalnutShortbread").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemAici = new FcFood(3, 8F, "ItemAici").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemStickyRiceCake = new FcFood(3, 7F, "ItemStickyRiceCake").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChangfen = new FcFood(3, 7F, "ItemChangfen").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemSausage = new FcFood(3, 6F, "ItemSausage").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemHotDog = new FcFood(3, 8F, "ItemHotDog").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChineseSausage = new FcFood(3, 8F, "ItemChineseSausage").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemChineseBacon = new FcFood(3, 9F, "ItemChineseBacon").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFriedSausage = new FcFood(3, 8F, "ItemFriedSausage").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemLaBaPorridge = new FcFood(3, 9F, "ItemLaBaPorridge").setCreativeTab(FoodCraft.FcTabStaple);	
		ItemCheese = new FcFood(3, 5F, "ItemCheese").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemPizza = new FcFood(3, 12F, "ItemPizza").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemHamburger = new FcFood(3, 12F, "ItemHamburger").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemSquidMeat = new FcFood(3, 8F, "ItemSquidMeat").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemCookedSquidMeat = new FcFood(3, 10F, "ItemCookedSquidMeat").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemSquidSlices = new FcFood(3, 3F, "ItemSquidSlices").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemVegetable = new FcFood(3, 3F, "ItemVegetable").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemTomato = new FcFood(3, 3F, "ItemTomato").setCreativeTab(FoodCraft.FcTabPlant);
		ItemGrapes = new FcFood(3, 3F, "ItemGrapes").setCreativeTab(FoodCraft.FcTabPlant);
		ItemEggplant = new FcFood(3, 3F, "ItemEggplant").setCreativeTab(FoodCraft.FcTabPlant);
		ItemQingjiao = new FcFood(3, 3F, "ItemQingjiao").setCreativeTab(FoodCraft.FcTabPlant);
		ItemYumi = new FcFood(3, 3F, "ItemYumi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemHuanggua = new FcFood(3, 3F, "ItemHuanggua").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemKaohongshu = new FcFood(3, 8F, "ItemKaohongshu").setCreativeTab(FoodCraft.FcTabSnack);
		ItemDoujiao = new FcFood(3, 3F, "ItemDoujiao").setCreativeTab(FoodCraft.FcTabPlant);
		ItemHongzao = new FcFood(3, 2F, "ItemHongzao").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemYezi = new FcFood(3, 2F, "ItemYezi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemYingtao = new FcFood(3, 2F, "ItemYingtao").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemXiangjiao = new FcFood(3, 2F, "ItemXiangjiao").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemKaoyumi = new FcFood(3, 6F, "ItemKaoyumi").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemBaoyumihua = new FcFood(3, 6F, "ItemBaoyumihua").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemLi = new FcFood(3, 2F, "ItemLi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemLizhi = new FcFood(3, 2F, "ItemLizhi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemTaozi = new FcFood(3, 2F, "ItemTaozi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemJuzi = new FcFood(3, 2F, "ItemJuzi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemPipa = new FcFood(3, 2F, "ItemPipa").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemMangguo = new FcFood(3, 2F, "ItemMangguo").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemNingmeng = new FcFood(3, 2F, "ItemNingmeng").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemYouzi = new FcFood(3, 2F, "ItemYouzi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemShizi = new FcFood(3, 2F, "ItemShizi").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemMugua = new FcFood(3, 2F, "ItemMugua").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemShanzha = new FcFood(3, 2F, "ItemShanzha").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemLongyan = new FcFood(3, 2F, "ItemLongyan").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemShiliu = new FcFood(3, 2F, "ItemShiliu").setCreativeTab(FoodCraft.FcTabPlant);	
		ItemBingganF = new FcFood(3, 6F, "ItemBingganF").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemBingganXN = new FcFood(3, 7F, "ItemBingganXN").setCreativeTab(FoodCraft.FcTabSnack);	
		ItemFanqiechaojidanfan = new ItemStapleFood(3, 18F, "ItemFanqiechaojidanfan");	
		ItemDisanxian = new ItemStapleFood(3, 18F, "ItemDisanxian");	
		ItemYuxiangrousi = new ItemStapleFood(3, 18F, "ItemYuxiangrousi");	
		ItemGongbaojiding = new ItemStapleFood(3, 18F, "ItemGongbaojiding");
		ItemChaotudousifan = new ItemStapleFood(3, 18F, "ItemChaotudousifan");
		ItemDuojiaoyutou = new ItemStapleFood(3, 18F, "ItemDuojiaoyutou");
		ItemMapodoufufan = new ItemStapleFood(3, 18F, "ItemMapodoufufan");
		ItemHongshaoroufan = new ItemStapleFood(3, 18F, "ItemHongshaoroufan");
		ItemHuiguoroufan = new ItemStapleFood(3, 18F, "ItemHuiguoroufan");
		ItemAeljichifan = new ItemStapleFood(3, 20F, "ItemAeljichifan");
		ItemBaiqiuji = new ItemStapleFood(3, 18F, "ItemBaiqiuji");
		ItemCongyouji = new ItemStapleFood(3, 18F, "ItemCongyouji");
		ItemKoushuiji = new ItemStapleFood(3, 18F, "ItemKoushuiji");
		ItemLaziji = new ItemStapleFood(3, 18F, "ItemLaziji");
		ItemQingzhenyu = new ItemStapleFood(3, 18F, "ItemQingzhenyu");
		ItemMalayu = new ItemStapleFood(3, 18F, "ItemMalayu");
		ItemSuancaiyu = new ItemStapleFood(3, 18F, "ItemSuancaiyu");
		ItemKelejichifan = new ItemStapleFood(3, 20F, "ItemKelejichifan");
		ItemGalijiroufan = new ItemStapleFood(3, 18F, "ItemGalijiroufan");
		ItemShuizhuniurou = new ItemStapleFood(3, 18F, "ItemShuizhuniurou");
		ItemPastaPork = new ItemStapleFood(3, 18F, "ItemPastaPork");
		ItemPastaBeef = new ItemStapleFood(3, 18F, "ItemPastaBeef");
		ItemPastaChicken = new ItemStapleFood(3, 18F, "ItemPastaChicken");
		ItemRibendoufu = new ItemStapleFood(3, 18F, "ItemRibendoufu");	
		ItemSoybeanMilk = new ItemDrink(2, 4F, "ItemSoybeanMilk", 16777215);
		ItemChocolatesWater = new ItemDrink(3, 7F, "ItemChocolatesWater",0x956844);
		ItemChocolatesMilk = new ItemDrink(3, 7F, "ItemChocolatesMilk",0xae927c);
		ItemCarrotJuice = new ItemDrink(3, 7F, "ItemCarrotJuice",0xf4872f);
		ItemGrapeJuice = new ItemDrink(3, 7F, "ItemGrapeJuice",0xbc18b6);
		ItemAppleJuice = new ItemDrink(3, 7F, "ItemAppleJuice",0xfa2059);
		ItemVegetableJuice = new ItemDrink(3, 7F, "ItemVegetableJuice",0x6abc19);
		ItemGoldenGrapeJuice = new ItemDrink(3, 20F, "ItemGoldenGrapeJuice",true , 0, 0xe0da42);
		ItemGoldenAppleJuice = new ItemDrink(3, 20F, "ItemGoldenAppleJuice",true , 1, 0xe7e480);
		ItemSoyMilk = new ItemDrink(3, 7F, "ItemSoyMilk",0xfafaf2);
		ItemCoke = new ItemDrink(3, 7F, "ItemCoke",0x512008);
		ItemSprite = new ItemDrink(3, 7F, "ItemSprite",0xededed);
		ItemChocolatesmilk_ice = new ItemDrink(3, 9F, "ItemChocolatesmilk_ice", 16777215).setAlwaysEdible();
		ItemGrapeJuice_ice = new ItemDrink(3, 9F, "ItemGrapeJuice_ice",0);
		ItemAppleJuice_ice = new ItemDrink(3, 9F, "ItemAppleJuice_ice",0);
		ItemGoldenGrapeJuice_ice = new ItemDrink(3, 9F, "ItemGoldenGrapeJuice_ice" , true , 0,0);
		ItemGoldenAppleJuice_ice = new ItemDrink(3, 9F, "ItemGoldenAppleJuice_ice" , true , 1,0);
		ItemMelonJuice = new ItemDrink(3, 7F, "ItemMelonJuice",0xe848b9);
		ItemMelonJuice_ice = new ItemDrink(3, 9F, "ItemMelonJuice_ice",0);
		ItemTea = new ItemDrink(3, 6F, "ItemTea",0x98a285);
		ItemMilkTea = new ItemDrink(3, 7F, "ItemMilkTea",0xc29833);
		ItemCoffee = new ItemDrink(3, 7F, "ItemCoffee",0x50462d);
		ItemBailuobozhi = new ItemDrink(3, 8F, "ItemBailuobozhi",0xfffbf3);
		ItemFanqiezhi = new ItemDrink(3, 8F, "ItemFanqiezhi",0xe1304d);
		ItemHuangguazhi = new ItemDrink(3, 8F, "ItemHuangguazhi",0xb1c28b);
		ItemYumizhi = new ItemDrink(3, 8F, "ItemYumizhi",0xebe47a);
		ItemLizizhi = new ItemDrink(3, 8F, "ItemLizizhi",0xe5db3b);
		ItemLizhizhi = new ItemDrink(3, 8F, "ItemLizhizhi",0xf6edd0);
		ItemTaozizhi = new ItemDrink(3, 8F, "ItemTaozizhi",0xf6cc24);
		ItemJuzizhi = new ItemDrink(3, 8F, "ItemJuzizhi",0xf6ae24);
		ItemPipazhi = new ItemDrink(3, 8F, "ItemPipazhi",0xfdcb6b);
		ItemMangguozhi = new ItemDrink(3, 8F, "ItemMangguozhi",0xffd986);
		ItemNingmengzhi = new ItemDrink(3, 8F, "ItemNingmengzhi",0xfcf393);
		ItemYouzizhi = new ItemDrink(3, 8F, "ItemYouzizhi",0xece382);
		ItemShizizhi = new ItemDrink(3, 8F, "ItemShizizhi",0xeb8c30);
		ItemMuguazhi = new ItemDrink(3, 8F, "ItemMuguazhi",0xf18a25);
		ItemShanzhazhi = new ItemDrink(3, 8F, "ItemShanzhazhi",0xea7b0e);
		ItemShiliuzhi = new ItemDrink(3, 8F, "ItemShiliuzhi",0xf46c30);
		ItemHongzaozhi = new ItemDrink(3, 8F, "ItemHongzaozhi",0xb57c63);
		ItemCaomeizhi = new ItemDrink(3, 8F, "ItemCaomeizhi",0xef1f6d);
		ItemYezizhi = new ItemDrink(3, 8F, "ItemYezizhi",0xfcf4d6);
		ItemYingtaozhi = new ItemDrink(3, 8F, "ItemYingtaozhi",0xfd6d0d);
		ItemXiangjiaozhi = new ItemDrink(3, 8F, "ItemXiangjiaozhi",0xf7eb6a);
		ItemYenai = new ItemDrink(3, 8F, "ItemYenai",0xfefdf4);
		ItemLizhizhiice = new ItemDrink(3, 9F, "ItemLizhizhiice",0);
		ItemTaozizhiice = new ItemDrink(3, 9F, "ItemTaozizhiice",0);
		ItemJuzizhiice = new ItemDrink(3, 9F, "ItemJuzizhiice",0);
		ItemMangguozhiice = new ItemDrink(3, 9F, "ItemMangguozhiice",0);
		ItemNingmengzhiice = new ItemDrink(3, 9F, "ItemNingmengzhiice",0);
		ItemMuguazhiice = new ItemDrink(3, 9F, "ItemMuguazhiice",0);
		ItemCaomeizhiice = new ItemDrink(3, 9F, "ItemCaomeizhiice",0);
		ItemYezizhiice = new ItemDrink(3, 9F, "ItemYezizhiice",0);
		ItemXiangjiaozhiice = new ItemDrink(3, 9F, "ItemXiangjiaozhiice",0);
		ItemRedWine = new ItemWine(3, 8F, "ItemRedWine").setAlwaysEdible();	
		ItemSpirit = new ItemWine(3, 8F, "ItemSpirit").setAlwaysEdible();
		ItemCider = new ItemWine(3, 8F, "ItemCider").setAlwaysEdible();
		ItemGrapeWine = new ItemWine(3, 8F, "ItemGrapeWine").setAlwaysEdible();
		ItemLizijiu = new ItemWine(3, 8F, "ItemLizijiu").setAlwaysEdible();	
		ItemLizhijiu = new ItemWine(3, 8F, "ItemLizhijiu").setAlwaysEdible();	
		ItemTaozijiu = new ItemWine(3, 8F, "ItemTaozijiu").setAlwaysEdible();	
		ItemMangguojiu = new ItemWine(3, 8F, "ItemMangguojiu").setAlwaysEdible();	
		ItemNingmengjiu = new ItemWine(3, 8F, "ItemNingmengjiu").setAlwaysEdible();	
		ItemShiliujiu = new ItemWine(3, 8F, "ItemShiliujiu").setAlwaysEdible();
		ItemGoldenGrapeWine = new ItemGoldenGrapeWine(3, 20F, "ItemGoldenGrapeWine").setAlwaysEdible();
		ItemGoldenCider = new ItemGoldenAppleWine(3, 20F, "ItemGoldenCider").setAlwaysEdible();
		ItemGuojiang = new ItemJam();
		ItemBinggan = new ItemCookie(3, 10F, "ItemBinggan");	
		ItemDangao = new ItemCakeFoodcraft();	
		ItemScallion = new ItemReed(FoodcraftPlants.BlockCong).setUnlocalizedName("ItemScallion").setCreativeTab(FoodCraft.FcTabPlant);MinecraftForge.addGrassSeed(new ItemStack(ItemScallion), 2);
		ItemChili = new ItemFoodChili();
		ItemKitchenKnife = new Item().setUnlocalizedName("ItemKitchenKnife").setCreativeTab(FoodCraft.FcTabMachine).setMaxDamage(59).setMaxStackSize(1);	
		ItemCaidaoHJ = new ItemKitchenKnifeGold();
		ItemCaidaoZS = new ItemKitchenKnifeDiamond();			
		ItemCaidaoLBS = new ItemKitchenKnifeEmerald();		
		ItemFoodcraftBucket = new ItemCleaningBucket(EnumHelper.addToolMaterial("JHST", 0, 16, 2.0F, 0.0F, 15));
		ItemWrench = new ItemWrench("ItemWrench");
		ItemTest = new ItemTest();	
		
		/**------------------------------ Machines and Tools  ------------------------------*/
		GameRegistry.registerItem(ItemIronSheet, "ItemIronSheet");
		GameRegistry.registerItem(ItemFoodcraftBucket, "ItemFoodcraftBucket");
		GameRegistry.registerItem(ItemMachineCore, "ItemMachineCore");
		GameRegistry.registerItem(ItemKitchenKnife, "ItemKitchenKnife");
		GameRegistry.registerItem(ItemCaidaoHJ, "ItemCaidaoHJ");
		GameRegistry.registerItem(ItemCaidaoZS, "ItemCaidaoZS");
		GameRegistry.registerItem(ItemCaidaoLBS, "ItemCaidaoLBS");
		GameRegistry.registerItem(ItemWrench, "ItemWrench");
		GameRegistry.registerItem(ItemJinkela, "ItemJinkela");
		GameRegistry.registerItem(ItemNull, "ItemNull");
		/**------------------------------ Plants  ------------------------------*/ 	
		GameRegistry.registerItem(ItemRice, "ItemRice");
		GameRegistry.registerItem(ItemPeanut, "ItemPeanut");	
		GameRegistry.registerItem(ItemBeans, "ItemBeans");	
		GameRegistry.registerItem(ItemStickyRice, "ItemStickyRice");
		GameRegistry.registerItem(ItemHongdou, "ItemHongdou");
		GameRegistry.registerItem(ItemLvdou, "ItemLvdou");
		GameRegistry.registerItem(ItemBailuobo, "ItemBailuobo");
		GameRegistry.registerItem(ItemVegetable, "ItemVegetable");	
		GameRegistry.registerItem(ItemChili, "ItemChili");	
		GameRegistry.registerItem(ItemQingjiao, "ItemQingjiao");
		GameRegistry.registerItem(ItemTomato, "ItemTomato");	
		GameRegistry.registerItem(ItemEggplant, "ItemEggplant");	
		GameRegistry.registerItem(ItemScallion, "ItemScallion");	
		GameRegistry.registerItem(ItemDoujiao, "ItemDoujiao");
		GameRegistry.registerItem(ItemHuanggua, "ItemHuanggua");
		GameRegistry.registerItem(ItemYumi, "ItemYumi");	
		GameRegistry.registerItem(ItemHongshu, "ItemHongshu");
		GameRegistry.registerItem(ItemZongye, "ItemZongye");
		GameRegistry.registerItem(ItemGrapes, "ItemGrapes");	
		GameRegistry.registerItem(ItemGoldenGrape, "ItemGoldenGrape");	
		GameRegistry.registerItem(ItemLi, "ItemLi");
		GameRegistry.registerItem(ItemLizhi, "ItemLizhi");
		GameRegistry.registerItem(ItemTaozi, "ItemTaozi");
		GameRegistry.registerItem(ItemJuzi, "ItemJuzi");
		GameRegistry.registerItem(ItemPipa, "ItemPipa");
		GameRegistry.registerItem(ItemMangguo, "ItemMangguo");
		GameRegistry.registerItem(ItemNingmeng, "ItemNingmeng");
		GameRegistry.registerItem(ItemYouzi, "ItemYouzi");
		GameRegistry.registerItem(ItemShizi, "ItemShizi");
		GameRegistry.registerItem(ItemMugua, "ItemMugua");
		GameRegistry.registerItem(ItemShanzha, "ItemShanzha");
		GameRegistry.registerItem(ItemLongyan, "ItemLongyan");
		GameRegistry.registerItem(ItemShiliu, "ItemShiliu");
		GameRegistry.registerItem(ItemHongzao, "ItemHongzao");
		GameRegistry.registerItem(ItemCaomei, "ItemCaomei");
		GameRegistry.registerItem(ItemYezi, "ItemYezi");
		GameRegistry.registerItem(ItemYingtao, "ItemYingtao");
		GameRegistry.registerItem(ItemXiangjiao, "ItemXiangjiao");
		GameRegistry.registerItem(ItemShucaizhong, "ItemShucaizhong");
		GameRegistry.registerItem(ItemLajiaozhong, "ItemLajiaozhong");
		GameRegistry.registerItem(ItemFanqiezhong, "ItemFanqiezhong");
		GameRegistry.registerItem(ItemPutaozhong, "ItemPutaozhong");
		GameRegistry.registerItem(ItemQiezizhong, "ItemQiezizhong");
		GameRegistry.registerItem(ItemQingjiaozhong, "ItemQingjiaozhong");
		GameRegistry.registerItem(ItemYumizhong, "ItemYumizhong");
		GameRegistry.registerItem(ItemHuangguazhong, "ItemHuangguazhong");
		/**------------------------------  Drinks  ------------------------------*/ 
		GameRegistry.registerItem(ItemSoybeanMilk, "ItemSoybeanMilk");
		GameRegistry.registerItem(ItemRedWine, "ItemRedWine");
		GameRegistry.registerItem(ItemSpirit, "ItemSpirit");
		GameRegistry.registerItem(ItemGrapeWine, "ItemGrapeWine");
		GameRegistry.registerItem(ItemCider, "ItemCider");		
		GameRegistry.registerItem(ItemGoldenGrapeWine, "ItemGoldenGrapeWine");
		GameRegistry.registerItem(ItemGoldenCider, "ItemGoldenCider");	
		GameRegistry.registerItem(ItemLizijiu, "ItemLizijiu");
		GameRegistry.registerItem(ItemLizhijiu, "ItemLizhijiu");
		GameRegistry.registerItem(ItemTaozijiu, "ItemTaozijiu");
		GameRegistry.registerItem(ItemMangguojiu, "ItemMangguojiu");
		GameRegistry.registerItem(ItemNingmengjiu, "ItemNingmengjiu");
		GameRegistry.registerItem(ItemShiliujiu, "ItemShiliujiu");
		GameRegistry.registerItem(ItemChocolatesWater, "ItemChocolatesWater");
		GameRegistry.registerItem(ItemCarrotJuice, "ItemCarrotJuice");
		GameRegistry.registerItem(ItemTea, "ItemTea");
		GameRegistry.registerItem(ItemGrapeJuice, "ItemGrapeJuice");
		GameRegistry.registerItem(ItemAppleJuice, "ItemAppleJuice");
		GameRegistry.registerItem(ItemVegetableJuice, "ItemVegetableJuice");
		GameRegistry.registerItem(ItemMelonJuice, "ItemMelonJuice");		
		GameRegistry.registerItem(ItemGoldenGrapeJuice, "ItemGoldenGrapeJuice");
		GameRegistry.registerItem(ItemGoldenAppleJuice, "ItemGoldenAppleJuice");
		GameRegistry.registerItem(ItemCoke, "ItemCoke");
		GameRegistry.registerItem(ItemSprite, "ItemSprite");
		GameRegistry.registerItem(ItemMilkTea, "ItemMilkTea");
		GameRegistry.registerItem(ItemCoffee, "ItemCoffee");		
		GameRegistry.registerItem(ItemChocolatesMilk, "ItemChocolatesMilk");
		GameRegistry.registerItem(ItemSoyMilk, "ItemSoyMilk");		
		GameRegistry.registerItem(ItemBailuobozhi, "ItemBailuobozhi");	
		GameRegistry.registerItem(ItemFanqiezhi, "ItemFanqiezhi");	
		GameRegistry.registerItem(ItemYumizhi, "ItemYumizhi");	
		GameRegistry.registerItem(ItemHuangguazhi, "ItemHuangguazhi");	
		GameRegistry.registerItem(ItemLizizhi, "ItemLizizhi");	
		GameRegistry.registerItem(ItemLizhizhi, "ItemLizhizhi");	
		GameRegistry.registerItem(ItemTaozizhi, "ItemTaozizhi");	
		GameRegistry.registerItem(ItemJuzizhi, "ItemJuzizhi");	
		GameRegistry.registerItem(ItemPipazhi, "ItemPipazhi");	
		GameRegistry.registerItem(ItemMangguozhi, "ItemMangguozhi");	
		GameRegistry.registerItem(ItemNingmengzhi, "ItemNingmengzhi");	
		GameRegistry.registerItem(ItemYouzizhi, "ItemYouzizhi");	
		GameRegistry.registerItem(ItemShizizhi, "ItemShizizhi");	
		GameRegistry.registerItem(ItemMuguazhi, "ItemMuguazhi");	
		GameRegistry.registerItem(ItemShanzhazhi, "ItemShanzhazhi");	
		GameRegistry.registerItem(ItemShiliuzhi, "ItemShiliuzhi");	
		GameRegistry.registerItem(ItemHongzaozhi, "ItemHongzaozhi");	
		GameRegistry.registerItem(ItemCaomeizhi, "ItemCaomeizhi");	
		GameRegistry.registerItem(ItemYezizhi, "ItemYezizhi");	
		GameRegistry.registerItem(ItemYingtaozhi, "ItemYingtaozhi");	
		GameRegistry.registerItem(ItemXiangjiaozhi, "ItemXiangjiaozhi");	
		GameRegistry.registerItem(ItemYenai, "ItemYenai");	
		GameRegistry.registerItem(ItemChocolatesmilk_ice, "ItemChocolatesmilk_ice");
		GameRegistry.registerItem(ItemGrapeJuice_ice, "ItemGrapeJuice_ice");
		GameRegistry.registerItem(ItemAppleJuice_ice, "ItemAppleJuice_ice");
		GameRegistry.registerItem(ItemGoldenGrapeJuice_ice, "ItemGoldenGrapeJuice_ice");
		GameRegistry.registerItem(ItemMelonJuice_ice, "ItemMelonJuice_ice");
		GameRegistry.registerItem(ItemGoldenAppleJuice_ice, "ItemGoldenAppleJuice_ice");
		GameRegistry.registerItem(ItemLizhizhiice, "ItemLizhizhiice");
		GameRegistry.registerItem(ItemTaozizhiice, "ItemTaozizhiice");
		GameRegistry.registerItem(ItemJuzizhiice, "ItemJuzizhiice");
		GameRegistry.registerItem(ItemMangguozhiice, "ItemMangguozhiice");
		GameRegistry.registerItem(ItemNingmengzhiice, "ItemNingmengzhiice");
		GameRegistry.registerItem(ItemMuguazhiice, "ItemMuguazhiice");
		GameRegistry.registerItem(ItemCaomeizhiice, "ItemCaomeizhiice");
		GameRegistry.registerItem(ItemYezizhiice, "ItemYezizhiice");
		GameRegistry.registerItem(ItemXiangjiaozhiice, "ItemXiangjiaozhiice");
		/**------------------------------  Staple Food  ------------------------------*/ 
		GameRegistry.registerItem(ItemMogudunjitang, "ItemMogudunjitang");
		GameRegistry.registerItem(ItemEggSoup, "ItemEggSoup");
		GameRegistry.registerItem(ItemNoodles, "ItemNoodles");
		GameRegistry.registerItem(ItemCrossingBridgeNoodles, "ItemCrossingBridgeNoodles");
		GameRegistry.registerItem(ItemPreservedEggPorridge, "ItemPreservedEggPorridge");
		GameRegistry.registerItem(ItemLaBaPorridge, "ItemLaBaPorridge");
		GameRegistry.registerItem(ItemFanqiechaojidanfan, "ItemFanqiechaojidanfan");
		GameRegistry.registerItem(ItemDisanxian, "ItemDisanxian");
		GameRegistry.registerItem(ItemYuxiangrousi, "ItemYuxiangrousi");
		GameRegistry.registerItem(ItemGongbaojiding, "ItemGongbaojiding");
		GameRegistry.registerItem(ItemChaotudousifan, "ItemChaotudousifan");
		GameRegistry.registerItem(ItemDuojiaoyutou, "ItemDuojiaoyutou");
		GameRegistry.registerItem(ItemMapodoufufan, "ItemMapodoufufan");
		GameRegistry.registerItem(ItemHongshaoroufan, "ItemHongshaoroufan");
		GameRegistry.registerItem(ItemHuiguoroufan, "ItemHuiguoroufan");
		GameRegistry.registerItem(ItemAeljichifan, "ItemAeljichifan");
		GameRegistry.registerItem(ItemLaziji, "ItemLaziji");
		GameRegistry.registerItem(ItemKoushuiji, "ItemKoushuiji");
		GameRegistry.registerItem(ItemBaiqiuji, "ItemBaiqiuji");
		GameRegistry.registerItem(ItemCongyouji, "ItemCongyouji");
		GameRegistry.registerItem(ItemSuancaiyu, "ItemSuancaiyu");
		GameRegistry.registerItem(ItemMalayu, "ItemMalayu");
		GameRegistry.registerItem(ItemQingzhenyu, "ItemQingzhenyu");
		GameRegistry.registerItem(ItemKelejichifan, "ItemKelejichifan");
		GameRegistry.registerItem(ItemGalijiroufan, "ItemGalijiroufan");
		GameRegistry.registerItem(ItemShuizhuniurou, "ItemShuizhuniurou");
		GameRegistry.registerItem(ItemPasta, "ItemPasta");
		GameRegistry.registerItem(ItemPastaPork, "ItemPastaPork");
		GameRegistry.registerItem(ItemPastaBeef, "ItemPastaBeef");
		GameRegistry.registerItem(ItemPastaChicken, "ItemPastaChicken");
		GameRegistry.registerItem(ItemRibendoufu, "ItemRibendoufu");
		GameRegistry.registerItem(ItemChangfen, "ItemChangfen");
		/**------------------------------  Ingredients    ------------------------------*/ 
		GameRegistry.registerItem(Itemwater, "Itemwater");
		GameRegistry.registerItem(ItemMilledRice, "ItemMilledRice");
		GameRegistry.registerItem(ItemFlour, "ItemFlour");
		GameRegistry.registerItem(ItemSalt, "ItemSalt");
		GameRegistry.registerItem(ItemDumplingWrappers, "ItemDumplingWrappers");
		GameRegistry.registerItem(ItemWatercress, "ItemWatercress");
		GameRegistry.registerItem(ItemChocolateDust, "ItemChocolateDust");
		GameRegistry.registerItem(ItemDumplingMeat, "ItemDumplingMeat");
		GameRegistry.registerItem(ItemPeanutOil, "ItemPeanutOil");
		GameRegistry.registerItem(ItemCookedRice, "ItemCookedRice");
		GameRegistry.registerItem(ItemDrumstick, "ItemDrumstick");	
		GameRegistry.registerItem(ItemChickenWing, "ItemChickenWing");	
		GameRegistry.registerItem(ItemBigChicken, "ItemBigChicken");	
		GameRegistry.registerItem(ItemMediumChicken, "ItemMediumChicken");	
		GameRegistry.registerItem(ItemSmallChicken, "ItemSmallChicken");	
		GameRegistry.registerItem(ItemPotatoChips, "ItemPotatoChips");	
		GameRegistry.registerItem(ItemPotatoesWire, "ItemPotatoesWire");	
		GameRegistry.registerItem(ItemSoySauce, "ItemSoySauce");	
		GameRegistry.registerItem(ItemVinegar, "ItemVinegar");	
		GameRegistry.registerItem(ItemDousha, "ItemDousha");
		GameRegistry.registerItem(ItemStarches, "ItemStarches");		
		GameRegistry.registerItem(ItemStickyRiceFlour, "ItemStickyRiceFlour");	
		GameRegistry.registerItem(ItemStickyRiceDough, "ItemStickyRiceDough");	
		GameRegistry.registerItem(ItemPeanutTangyuanStuffing, "ItemPeanutTangyuanStuffing");	
		GameRegistry.registerItem(ItemTofuStrip, "ItemTofuStrip");	
		GameRegistry.registerItem(ItemCarrotStrip, "ItemCarrotStrip");	
		GameRegistry.registerItem(ItemBailuobosi, "ItemBailuobosi");	
		GameRegistry.registerItem(ItemFlourSilk, "ItemFlourSilk");	
		GameRegistry.registerItem(ItemBlockCurry, "ItemBlockCurry");	
		GameRegistry.registerItem(ItemSmokedMaterial, "ItemSmokedMaterial");			
		GameRegistry.registerItem(ItemGuojiang, "ItemGuojiang");
		GameRegistry.registerItem(ItemShaojiaodeshiwu, "ItemShaojiaodeshiwu");
		/**------------------------------  Snacks   ------------------------------*/ 
		GameRegistry.registerItem(ItemSquidMeat, "ItemSquidMeat");
		GameRegistry.registerItem(ItemCookedSquidMeat, "ItemCookedSquidMeat");
		GameRegistry.registerItem(ItemSquidSlices, "ItemSquidSlices");		
		GameRegistry.registerItem(ItemPoachedEgg, "ItemPoachedEgg");		
		GameRegistry.registerItem(ItemPancakes, "ItemPancakes");
		GameRegistry.registerItem(ItemDumpling, "ItemDumpling");
		GameRegistry.registerItem(ItemFriedDumpling, "ItemFriedDumpling");
		GameRegistry.registerItem(ItemTofu, "ItemTofu");
		GameRegistry.registerItem(ItemDriedTofu, "ItemDriedTofu");
		GameRegistry.registerItem(ItemFriedPotatoChips, "ItemFriedPotatoChips");
		GameRegistry.registerItem(ItemPorridge, "ItemPorridge");
		GameRegistry.registerItem(ItemStickyRiceDumpling, "ItemStickyRiceDumpling");
		GameRegistry.registerItem(ItemMooncake, "ItemMooncake");
		GameRegistry.registerItem(ItemTangyuan, "ItemTangyuan");
		GameRegistry.registerItem(ItemDoughTwist, "ItemDoughTwist");
		GameRegistry.registerItem(ItemSpringRolls, "ItemSpringRolls");
		GameRegistry.registerItem(ItemChips, "ItemChips");
		GameRegistry.registerItem(ItemSausage, "ItemSausage");
		GameRegistry.registerItem(ItemChineseSausage, "ItemChineseSausage");
		GameRegistry.registerItem(ItemChineseBacon, "ItemChineseBacon");
		GameRegistry.registerItem(ItemFriedSausage, "ItemFriedSausage");
		GameRegistry.registerItem(ItemPizza, "ItemPizza");
		GameRegistry.registerItem(ItemHamburger, "ItemHamburger");		
		GameRegistry.registerItem(ItemYoutiao, "ItemYoutiao");
		GameRegistry.registerItem(ItemChiliTofuStrip, "ItemChiliTofuStrip");		
		GameRegistry.registerItem(ItemFriedChicken, "ItemFriedChicken");
		GameRegistry.registerItem(ItemOriginalRecipe, "ItemOriginalRecipe");
		GameRegistry.registerItem(ItemFrenchFries, "ItemFrenchFries");
		GameRegistry.registerItem(ItemPopcornChicken, "ItemPopcornChicken");
		GameRegistry.registerItem(ItemOrleansWing, "ItemOrleansWing");		
		GameRegistry.registerItem(ItemFriedTofu, "ItemFriedTofu");
		GameRegistry.registerItem(ItemFriedSpringRolls, "ItemFriedSpringRolls");
		GameRegistry.registerItem(ItemFriedDoughTwist, "ItemFriedDoughTwist");
		GameRegistry.registerItem(ItemFriedDrumstick, "ItemFriedDrumstick");
		GameRegistry.registerItem(ItemKaohongshu, "ItemKaohongshu");
		GameRegistry.registerItem(ItemKaoyumi, "ItemKaoyumi");
		GameRegistry.registerItem(ItemBaoyumihua, "ItemBaoyumihua");
		/**------------------------------  Snacks    ------------------------------*/ 
		GameRegistry.registerItem(ItemChocolate, "ItemChocolate");
		GameRegistry.registerItem(ItemNewYearCake, "ItemNewYearCake");
		GameRegistry.registerItem(ItemWalnutShortbread, "ItemWalnutShortbread");
		GameRegistry.registerItem(ItemAici, "ItemAici");
		GameRegistry.registerItem(ItemStickyRiceCake, "ItemStickyRiceCake");
		GameRegistry.registerItem(ItemCheese, "ItemCheese");
		GameRegistry.registerItem(ItemSteamedBuns, "ItemSteamedBuns");
		GameRegistry.registerItem(ItemSauerkrautCake, "ItemSauerkrautCake");
		GameRegistry.registerItem(ItemFriedNewYearCake, "ItemFriedNewYearCake");
		GameRegistry.registerItem(ItemFriedBread, "ItemFriedBread");
		GameRegistry.registerItem(ItemHotDog, "ItemHotDog");
		GameRegistry.registerItem(ItemBingganXN, "ItemBingganXN");
		GameRegistry.registerItem(ItemBingganF, "ItemBingganF");
		GameRegistry.registerItem(ItemBinggan, "ItemBinggan");
		GameRegistry.registerItem(ItemDangao, "ItemDangao");
		/**------------------------------------------------------------------------*/ 
	}
}