package com.foodcraft.init;

import com.foodcraft.FoodCraft;
import com.foodcraft.item.*;
import com.foodcraft.plant.items.ItemPlant;
import com.foodcraft.plant.items.ItemSweetPotato;
import net.minecraft.item.Item;
import net.minecraft.item.ItemReed;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class FoodcraftItems {

    public static Item ItemCong,ItemZongye,ItemXifan,ItemDangeng,ItemTiepian,ItemCaidao,ItemDami,Itemfan,ItemMianfen,ItemHuashen,
           ItemDouzi,ItemHuashenyou,ItemDoujiang,ItemDianluban,ItemJianjidan,ItemLaobing,ItemMianpi,ItemJiaozixian,ItemJiaozi,ItemJianjiao,
           ItemQiaokeli,ItemQiaokelifen,ItemShucai,ItemFanqie,ItemLajiao,ItemMianfensi,ItemQiezi,ItemPutao,ItemYan,Itemwater,ItemDoufu,
           ItemJiangyou,ItemNuomi, ItemDoufugan,ItemBaifan,ItemFanqiechaojidanfan,ItemDisanxian,ItemCu,ItemYuxiangrousi,ItemGongbaojiding,
           ItemJitui,ItemTudoupian,ItemTudousi,ItemChaotudousifan,ItemChaotudoupian,ItemDuojiaoyutou,ItemDouban,ItemMapodoufufan,
           ItemDianfen,ItemHongshaoroufan,ItemHuiguoroufan,ItemMogudunjitang,ItemZongzi,ItemNuomifen,ItemTangyuan,
           ItemHuashentangyuanxian,ItemNuomituan,ItemMahua,ItemNiangao,ItemChunjuan,ItemJikuai,ItemShutiao,ItemAeljichi,ItemJimihua,
           ItemAeljichifan,ItemYuanweijikuai,ItemZhadoufu,ItemZhaniangao,ItemShupian,ItemZhamianbao,ItemZhachunjuan,ItemZhamahua,
           ItemZhajitui,ItemDajirou,ItemZhongjirou,ItemXiaojirou,ItemJichi,ItemDoufusi,ItemLuobosi,ItemHongjiu,ItemBaijiu,ItemPingguojiu,
           ItemPutaojiu,ItemJinputaojiu, ItemJinpingguojiu,ItemJinputao,ItemQiaokelishui,ItemQiaokelinai,ItemHuluobozhi,ItemPutaozhi,
           ItemPingguozhi,ItemShucaizhi,ItemJinputaozhi,ItemJinpingguozhi,ItemDounai,ItemKele,ItemXuebi,ItemXiguazhi,ItemQiaokelinaiice,
           ItemPutaozhiice,ItemPingguozhiice,ItemJinputaozhiice,ItemJinpingguozhiice,ItemXiguazhiice,ItemCha,ItemNaicha,ItemKafei,
           ItemBaiqiuji,ItemCongyouji,ItemKoushuiji,ItemLaziji,ItemQingzhenyu,ItemMalayu,ItemSuancaiyu,ItemKelejichifan,ItemGalikuai,
           ItemGalijiroufan,ItemShuizhuniurou,ItemMian,ItemGuoqiaomixian,ItemYifen,ItemYifenpork,ItemYifenbeef,ItemYifenchicken,
           ItemPidanshourouzhou,ItemYuebing,ItemMantou,ItemSuancaibing,ItemYoutiao,ItemLatiao,ItemHetaosu,ItemAici,ItemCiba,ItemChangfen,
           ItemXiangchang,ItemRegou,ItemLachang,ItemLarou,ItemZhaxiangchang,ItemRibendoufu,ItemLabazhou,ItemLaweixunliao,ItemNainao,
           ItemPisa,ItemHanbaobao,ItemJinghuashuitong,ItemNull,
           ItemYouyurou,ItemShuyouyurou,ItemYouyusi,ItemShucaizhong,ItemLajiaozhong,ItemFanqiezhong,ItemPutaozhong,ItemQiezizhong,ItemBailuobo,
           ItemQingjiao,ItemQingjiaozhong,ItemHongdou,ItemLvdou,ItemHongshu,ItemKaohongshu,ItemDoujiao,ItemWrench,ItemHuanggua,ItemHuangguazhong,
           ItemYumizhong,ItemYumi,ItemBailuobosi,ItemBailuobozhi,ItemFanqiezhi,ItemYumizhi,ItemHuangguazhi,ItemDousha,ItemKaoyumi,ItemBaoyumihua,
           ItemLi,ItemLizhi,ItemTaozi,ItemJuzi,ItemPipa,ItemMangguo,ItemNingmeng,ItemYouzi,ItemShizi,ItemMugua,ItemShanzha,ItemLongyan,ItemShiliu,
           ItemCaomei,ItemHongzao,ItemYezi,ItemYingtao,ItemXiangjiao,ItemJinkela,ItemLizizhi,ItemLizhizhi,ItemTaozizhi,ItemJuzizhi,ItemPipazhi,
           ItemMangguozhi,ItemNingmengzhi,ItemYouzizhi,ItemShizizhi,ItemMuguazhi,ItemShanzhazhi,ItemShiliuzhi,ItemHongzaozhi,ItemCaomeizhi,
           ItemYezizhi,ItemYingtaozhi,ItemXiangjiaozhi,ItemYenai,ItemLizhizhiice,ItemTaozizhiice,ItemJuzizhiice,ItemMangguozhiice,
           ItemNingmengzhiice,ItemMuguazhiice,ItemCaomeizhiice,ItemYezizhiice,ItemXiangjiaozhiice,ItemLizijiu,ItemLizhijiu,
           ItemTaozijiu,ItemMangguojiu,ItemNingmengjiu,ItemShiliujiu,ItemGuojiang,ItemBinggan,ItemDangao,
           ItemCaidaoHJ,ItemCaidaoZS,ItemCaidaoLBS,ItemBingganF,ItemBingganXN,ItemShaojiaodeshiwu,ItemTest;

    public static void init() {
        ItemTiepian = new ItemFc("ItemTiepian").setCreativeTab(FoodCraft.FcTabMachine);
        Itemwater = new ItemFc("Itemwater").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemNull = new ItemFc("ItemNull");
        Itemfan = new ItemFc("Itemfan").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemMianfen = new ItemFc("ItemMianfen").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemHuashenyou = new ItemFc("ItemHuashenyou").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDianluban = new ItemFc("ItemDianluban").setCreativeTab(FoodCraft.FcTabMachine);
        ItemMianpi = new ItemFc("ItemMianpi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemJiaozixian = new ItemFc("ItemJiaozixian").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemQiaokelifen = new ItemFc("ItemQiaokelifen").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemYan = new ItemFc("ItemYan").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemJiangyou = new ItemFc("ItemJiangyou").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemCu = new ItemFc("ItemCu").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemTudoupian = new ItemFc("ItemTudoupian").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemTudousi = new ItemFc("ItemTudousi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDouban = new ItemFc("ItemDouban").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDianfen = new ItemFc("ItemDianfen").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemZongye = new ItemFc("ItemZongye").setCreativeTab(FoodCraft.FcTabPlant);
        ItemNuomifen = new ItemFc("ItemNuomifen").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemNuomituan = new ItemFc("ItemNuomituan").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemHuashentangyuanxian = new ItemFc("ItemHuashentangyuanxian").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDajirou = new ItemFc("ItemDajirou").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemZhongjirou = new ItemFc("ItemZhongjirou").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemXiaojirou = new ItemFc("ItemXiaojirou").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDoufusi = new ItemFc("ItemDoufusi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemLuobosi = new ItemFc("ItemLuobosi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemMianfensi = new ItemFc("ItemMianfensi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemLaweixunliao = new ItemFc("ItemLaweixunliao").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemBailuobosi = new ItemFc("ItemBailuobosi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDousha = new ItemFc("ItemDousha").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemJinkela = new ItemFc("ItemJinkela").setCreativeTab(FoodCraft.FcTabMachine);
        ItemShaojiaodeshiwu = new ItemFc("ItemShaojiaodeshiwu").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemDami = new ItemPlant(FoodcraftPlants.BlockShuidao, "ItemDami");
        ItemHuashen = new ItemPlant(FoodcraftPlants.BlockHuashen, "ItemHuashen");
        ItemShucaizhong = new ItemPlant(FoodcraftPlants.BlockShucai, "ItemShucaizhong");
        ItemDouzi = new ItemPlant(FoodcraftPlants.BlockDouzi, "ItemDouzi");
        ItemLajiaozhong = new ItemPlant(FoodcraftPlants.BlockLajiao, "ItemLajiaozhong");
        ItemFanqiezhong = new ItemPlant(FoodcraftPlants.BlockFanqie, "ItemFanqiezhong");
        ItemPutaozhong = new ItemPlant(FoodcraftPlants.BlockPutao, "ItemPutaozhong");
        ItemQiezizhong = new ItemPlant(FoodcraftPlants.BlockQiezi, "ItemQiezizhong");
        ItemQingjiaozhong = new ItemPlant(FoodcraftPlants.BlockQingjiao, "ItemQingjiaozhong");
        ItemHongdou = new ItemPlant(FoodcraftPlants.BlockHongdou, "ItemHongdou");
        ItemLvdou = new ItemPlant(FoodcraftPlants.BlockLvdou,"ItemLvdou");
        ItemYumizhong = new ItemPlant(FoodcraftPlants.BlockYumi,"ItemYumizhong");
        ItemHuangguazhong = new ItemPlant(FoodcraftPlants.BlockHuanggua, "ItemHuangguazhong");
        ItemNuomi = new ItemPlant(FoodcraftPlants.BlockNuodao, "ItemNuomi");
        ItemCaomei = new ItemSweetPotato(FoodcraftPlants.BlockCaomei,3,"ItemCaomei");
        ItemBailuobo = new ItemSweetPotato(FoodcraftPlants.BlockBailuobo,3,"ItemBailuobo");
        ItemHongshu = new ItemSweetPotato(FoodcraftPlants.BlockHongshu,3,"ItemHongshu");
        ItemJianjidan = new FcFood(3, 5F, "ItemJianjidan").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLaobing = new FcFood(3, 5F, "ItemLaobing").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJiaozi = new FcFood(3, 8F, "ItemJiaozi").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJianjiao = new FcFood(3, 10F, "ItemJianJiao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemQiaokeli = new FcFood(3, 4F, "ItemQiaokeli").setCreativeTab(FoodCraft.FcTabSnack);
        ItemDoufu = new FcFood(3, 4F, "ItemDoufu").setCreativeTab(FoodCraft.FcTabSnack);
        ItemDoufugan = new FcFood(3, 6F, "ItemDoufugan").setCreativeTab(FoodCraft.FcTabSnack);
        ItemBaifan = new FcFood(3, 3F, "ItemBaifan").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemChaotudoupian = new FcFood(3, 7F, "ItemChaotudoupian").setCreativeTab(FoodCraft.FcTabSnack);
        ItemXifan = new FcFood(3, 7F, "ItemXifan").setCreativeTab(FoodCraft.FcTabStaple);
        ItemDangeng = new FcFood(3, 8F, "ItemDangeng").setCreativeTab(FoodCraft.FcTabStaple);
        ItemMogudunjitang = new FcFood(3, 8F, "ItemMogudunjitang").setCreativeTab(FoodCraft.FcTabStaple);
        ItemZongzi = new FcFood(3, 8F, "ItemZongzi").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJitui = new FcFood(3, 3F, "ItemJitui").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemTangyuan = new FcFood(3, 8F, "ItemTangyuan").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJikuai = new FcFood(3, 6F, "ItemJikuai").setCreativeTab(FoodCraft.FcTabSnack);
        ItemShutiao = new FcFood(3, 7F, "ItemShutiao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemAeljichi = new FcFood(3, 8F, "ItemAeljichi").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJimihua = new FcFood(3, 4F, "ItemJimihua").setCreativeTab(FoodCraft.FcTabSnack);
        ItemYuanweijikuai = new FcFood(3, 8F, "ItemYuanweijikuai").setCreativeTab(FoodCraft.FcTabSnack);
        ItemMahua = new FcFood(3, 7F, "ItemMahua").setCreativeTab(FoodCraft.FcTabSnack);
        ItemNiangao = new FcFood(3, 8F, "ItemNiangao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemChunjuan = new FcFood(3, 8F, "ItemChunjuan").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhadoufu = new FcFood(3, 6F, "ItemZhadoufu").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhaniangao = new FcFood(3, 10F, "ItemZhaniangao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemShupian = new FcFood(3, 7F, "ItemShupian").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhamianbao = new FcFood(3, 7F, "ItemZhamianbao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhachunjuan = new FcFood(3, 10F, "ItemZhachunjuan").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhamahua = new FcFood(3, 10F, "ItemZhamahua").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhajitui = new FcFood(3, 5F, "ItemZhajitui").setCreativeTab(FoodCraft.FcTabSnack);
        ItemJichi = new FcFood(3, 4F, "ItemJichi").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemJinputao = new FcFood(3, 20F, "ItemJinputao" ,true).setCreativeTab(FoodCraft.FcTabPlant);
        ItemGalikuai = new FcFood(3, 3F, "ItemGalikuai").setCreativeTab(FoodCraft.FcTabIngredient);
        ItemMian = new FcFood(3, 7F, "ItemMian").setCreativeTab(FoodCraft.FcTabStaple);
        ItemGuoqiaomixian = new FcFood(3, 7F, "ItemGuoqiaomixian").setCreativeTab(FoodCraft.FcTabStaple);
        ItemYifen = new FcFood(3, 7F, "ItemYifen").setCreativeTab(FoodCraft.FcTabStaple);
        ItemPidanshourouzhou = new FcFood(3, 7F, "ItemPidanshourouzhou").setCreativeTab(FoodCraft.FcTabStaple);
        ItemYuebing = new FcFood(3, 8F, "ItemYuebing").setCreativeTab(FoodCraft.FcTabSnack);
        ItemMantou = new FcFood(3, 4F, "ItemMantou").setCreativeTab(FoodCraft.FcTabSnack);
        ItemSuancaibing = new FcFood(3, 7F, "ItemSuancaibing").setCreativeTab(FoodCraft.FcTabSnack);
        ItemYoutiao = new FcFood(3, 8F, "ItemYoutiao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLatiao = new FcFood(3, 4F, "ItemLatiao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemHetaosu = new FcFood(3, 8F, "ItemHetaosu").setCreativeTab(FoodCraft.FcTabSnack);
        ItemAici = new FcFood(3, 8F, "ItemAici").setCreativeTab(FoodCraft.FcTabSnack);
        ItemCiba = new FcFood(3, 7F, "ItemCiba").setCreativeTab(FoodCraft.FcTabSnack);
        ItemChangfen = new FcFood(3, 7F, "ItemChangfen").setCreativeTab(FoodCraft.FcTabStaple);
        ItemXiangchang = new FcFood(3, 6F, "ItemXiangchang").setCreativeTab(FoodCraft.FcTabSnack);
        ItemRegou = new FcFood(3, 8F, "ItemRegou").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLachang = new FcFood(3, 8F, "ItemLachang").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLarou = new FcFood(3, 9F, "ItemLarou").setCreativeTab(FoodCraft.FcTabSnack);
        ItemZhaxiangchang = new FcFood(3, 8F, "ItemZhaxiangchang").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLabazhou = new FcFood(3, 9F, "ItemLabazhou").setCreativeTab(FoodCraft.FcTabStaple);
        ItemNainao = new FcFood(3, 5F, "ItemNainao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemPisa = new FcFood(3, 12F, "ItemPisa").setCreativeTab(FoodCraft.FcTabSnack);
        ItemHanbaobao = new FcFood(3, 12F, "ItemHanbaobao").setCreativeTab(FoodCraft.FcTabSnack);
        ItemYouyurou = new FcFood(3, 8F, "ItemYouyurou").setCreativeTab(FoodCraft.FcTabSnack);
        ItemShuyouyurou = new FcFood(3, 10F, "ItemShuyouyurou").setCreativeTab(FoodCraft.FcTabSnack);
        ItemYouyusi = new FcFood(3, 3F, "ItemYouyusi").setCreativeTab(FoodCraft.FcTabSnack);
        ItemShucai = new FcFood(3, 3F, "ItemShucai").setCreativeTab(FoodCraft.FcTabPlant);
        ItemFanqie = new FcFood(3, 3F, "ItemFanqie").setCreativeTab(FoodCraft.FcTabPlant);
        ItemPutao = new FcFood(3, 3F, "ItemPutao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemQiezi = new FcFood(3, 3F, "ItemQiezi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemQingjiao = new FcFood(3, 3F, "ItemQingjiao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemYumi = new FcFood(3, 3F, "ItemYumi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemHuanggua = new FcFood(3, 3F, "ItemHuanggua").setCreativeTab(FoodCraft.FcTabPlant);
        ItemKaohongshu = new FcFood(3, 8F, "ItemKaohongshu").setCreativeTab(FoodCraft.FcTabSnack);
        ItemDoujiao = new FcFood(3, 3F, "ItemDoujiao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemHongzao = new FcFood(3, 2F, "ItemHongzao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemYezi = new FcFood(3, 2F, "ItemYezi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemYingtao = new FcFood(3, 2F, "ItemYingtao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemXiangjiao = new FcFood(3, 2F, "ItemXiangjiao").setCreativeTab(FoodCraft.FcTabPlant);
        ItemKaoyumi = new FcFood(3, 6F, "ItemKaoyumi").setCreativeTab(FoodCraft.FcTabSnack);
        ItemBaoyumihua = new FcFood(3, 6F, "ItemBaoyumihua").setCreativeTab(FoodCraft.FcTabSnack);
        ItemLi = new FcFood(3, 2F, "ItemLi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemLizhi = new FcFood(3, 2F, "ItemLizhi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemTaozi = new FcFood(3, 2F, "ItemTaozi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemJuzi = new FcFood(3, 2F, "ItemJuzi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemPipa = new FcFood(3, 2F, "ItemPipa").setCreativeTab(FoodCraft.FcTabPlant);
        ItemMangguo = new FcFood(3, 2F, "ItemMangguo").setCreativeTab(FoodCraft.FcTabPlant);
        ItemNingmeng = new FcFood(3, 2F, "ItemNingmeng").setCreativeTab(FoodCraft.FcTabPlant);
        ItemYouzi = new FcFood(3, 2F, "ItemYouzi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemShizi = new FcFood(3, 2F, "ItemShizi").setCreativeTab(FoodCraft.FcTabPlant);
        ItemMugua = new FcFood(3, 2F, "ItemMugua").setCreativeTab(FoodCraft.FcTabPlant);
        ItemShanzha = new FcFood(3, 2F, "ItemShanzha").setCreativeTab(FoodCraft.FcTabPlant);
        ItemLongyan = new FcFood(3, 2F, "ItemLongyan").setCreativeTab(FoodCraft.FcTabPlant);
        ItemShiliu = new FcFood(3, 2F, "ItemShiliu").setCreativeTab(FoodCraft.FcTabPlant);
        ItemBingganF = new FcFood(3, 6F, "ItemBingganF").setCreativeTab(FoodCraft.FcTabSnack);
        ItemBingganXN = new FcFood(3, 7F, "ItemBingganXN").setCreativeTab(FoodCraft.FcTabSnack);
        ItemFanqiechaojidanfan = new ItemStapleFood(3, 18F, "ItemFanqiechaojidanfan");
        ItemDisanxian = new ItemStapleFood(3, 18F, "ItemDisanxian");
        ItemYuxiangrousi = new ItemStapleFood(3, 18F, "ItemYuxiangrousi");
        ItemGongbaojiding = new ItemStapleFood(3, 18F, "ItemGongbaojiding");
        ItemChaotudousifan = new ItemStapleFood(3, 18F, "ItemChaotudousifan");
        ItemDuojiaoyutou = new ItemStapleFood(3, 18F, "ItemDuojiaoyutou");
        ItemMapodoufufan = new ItemStapleFood(3, 18F, "ItemMapodoufufan");
        ItemHongshaoroufan = new ItemStapleFood(3, 18F, "ItemHongshaoroufan");
        ItemHuiguoroufan = new ItemStapleFood(3, 18F, "ItemHuiguoroufan");
        ItemAeljichifan = new ItemStapleFood(3, 20F, "ItemAeljichifan");
        ItemBaiqiuji = new ItemStapleFood(3, 18F, "ItemBaiqiuji");
        ItemCongyouji = new ItemStapleFood(3, 18F, "ItemCongyouji");
        ItemKoushuiji = new ItemStapleFood(3, 18F, "ItemKoushuiji");
        ItemLaziji = new ItemStapleFood(3, 18F, "ItemLaziji");
        ItemQingzhenyu = new ItemStapleFood(3, 18F, "ItemQingzhenyu");
        ItemMalayu = new ItemStapleFood(3, 18F, "ItemMalayu");
        ItemSuancaiyu = new ItemStapleFood(3, 18F, "ItemSuancaiyu");
        ItemKelejichifan = new ItemStapleFood(3, 20F, "ItemKelejichifan");
        ItemGalijiroufan = new ItemStapleFood(3, 18F, "ItemGalijiroufan");
        ItemShuizhuniurou = new ItemStapleFood(3, 18F, "ItemShuizhuniurou");
        ItemYifenpork = new ItemStapleFood(3, 18F, "ItemYifenpork");
        ItemYifenbeef = new ItemStapleFood(3, 18F, "ItemYifenbeef");
        ItemYifenchicken = new ItemStapleFood(3, 18F, "ItemYifenchicken");
        ItemRibendoufu = new ItemStapleFood(3, 18F, "ItemRibendoufu");
        ItemDoujiang = new ItemDrink(2, 4F, "ItemDoujiang", 16777215);
        ItemQiaokelishui = new ItemDrink(3, 7F, "ItemQiaokelishui",0x956844);
        ItemQiaokelinai = new ItemDrink(3, 7F, "ItemQiaokelinai",0xae927c);
        ItemHuluobozhi = new ItemDrink(3, 7F, "ItemHuluobozhi",0xf4872f);
        ItemPutaozhi = new ItemDrink(3, 7F, "ItemPutaozhi",0xbc18b6);
        ItemPingguozhi = new ItemDrink(3, 7F, "ItemPingguozhi",0xfa2059);
        ItemShucaizhi = new ItemDrink(3, 7F, "ItemShucaizhi",0x6abc19);
        ItemJinputaozhi = new ItemDrink(3, 20F, "ItemJinputaozhi",true , 0, 0xe0da42);
        ItemJinpingguozhi = new ItemDrink(3, 20F, "ItemJinpingguozhi",true , 1, 0xe7e480);
        ItemDounai = new ItemDrink(3, 7F, "ItemDounai",0xfafaf2);
        ItemKele = new ItemDrink(3, 7F, "ItemKele",0x512008);
        ItemXuebi = new ItemDrink(3, 7F, "ItemXuebi",0xededed);
        ItemQiaokelinaiice = new ItemDrink(3, 9F, "ItemQiaokelinaiice", 16777215).setAlwaysEdible();
        ItemPutaozhiice = new ItemDrink(3, 9F, "ItemPutaozhiice",0);
        ItemPingguozhiice = new ItemDrink(3, 9F, "ItemPingguozhiice",0);
        ItemJinputaozhiice = new ItemDrink(3, 9F, "ItemJinputaozhiice" , true , 0,0);
        ItemJinpingguozhiice = new ItemDrink(3, 9F, "ItemJinpingguozhiice" , true , 1,0);
        ItemXiguazhi = new ItemDrink(3, 7F, "ItemXiguazhi",0xe848b9);
        ItemXiguazhiice = new ItemDrink(3, 9F, "ItemXiguazhiice",0);
        ItemCha = new ItemDrink(3, 6F, "ItemCha",0x98a285);
        ItemNaicha = new ItemDrink(3, 7F, "ItemXiguazhi",0xc29833);
        ItemKafei = new ItemDrink(3, 7F, "ItemKafei",0x50462d);
        ItemBailuobozhi = new ItemDrink(3, 8F, "ItemBailuobozhi",0xfffbf3);
        ItemFanqiezhi = new ItemDrink(3, 8F, "ItemFanqiezhi",0xe1304d);
        ItemHuangguazhi = new ItemDrink(3, 8F, "ItemHuangguazhi",0xb1c28b);
        ItemYumizhi = new ItemDrink(3, 8F, "ItemYumizhi",0xebe47a);
        ItemLizizhi = new ItemDrink(3, 8F, "ItemLizizhi",0xe5db3b);
        ItemLizhizhi = new ItemDrink(3, 8F, "ItemLizhizhi",0xf6edd0);
        ItemTaozizhi = new ItemDrink(3, 8F, "ItemTaozizhi",0xf6cc24);
        ItemJuzizhi = new ItemDrink(3, 8F, "ItemJuzizhi",0xf6ae24);
        ItemPipazhi = new ItemDrink(3, 8F, "ItemPipazhi",0xfdcb6b);
        ItemMangguozhi = new ItemDrink(3, 8F, "ItemMangguozhi",0xffd986);
        ItemNingmengzhi = new ItemDrink(3, 8F, "ItemNingmengzhi",0xfcf393);
        ItemYouzizhi = new ItemDrink(3, 8F, "ItemYouzizhi",0xece382);
        ItemShizizhi = new ItemDrink(3, 8F, "ItemShizizhi",0xeb8c30);
        ItemMuguazhi = new ItemDrink(3, 8F, "ItemMuguazhi",0xf18a25);
        ItemShanzhazhi = new ItemDrink(3, 8F, "ItemShanzhazhi",0xea7b0e);
        ItemShiliuzhi = new ItemDrink(3, 8F, "ItemShiliuzhi",0xf46c30);
        ItemHongzaozhi = new ItemDrink(3, 8F, "ItemHongzaozhi",0xb57c63);
        ItemCaomeizhi = new ItemDrink(3, 8F, "ItemCaomeizhi",0xef1f6d);
        ItemYezizhi = new ItemDrink(3, 8F, "ItemYezizhi",0xfcf4d6);
        ItemYingtaozhi = new ItemDrink(3, 8F, "ItemYingtaozhi",0xfd6d0d);
        ItemXiangjiaozhi = new ItemDrink(3, 8F, "ItemXiangjiaozhi",0xf7eb6a);
        ItemYenai = new ItemDrink(3, 8F, "ItemYenai",0xfefdf4);
        ItemLizhizhiice = new ItemDrink(3, 9F, "ItemLizhizhiice",0);
        ItemTaozizhiice = new ItemDrink(3, 9F, "ItemTaozizhiice",0);
        ItemJuzizhiice = new ItemDrink(3, 9F, "ItemJuzizhiice",0);
        ItemMangguozhiice = new ItemDrink(3, 9F, "ItemMangguozhiice",0);
        ItemNingmengzhiice = new ItemDrink(3, 9F, "ItemNingmengzhiice",0);
        ItemMuguazhiice = new ItemDrink(3, 9F, "ItemMuguazhiice",0);
        ItemCaomeizhiice = new ItemDrink(3, 9F, "ItemCaomeizhiice",0);
        ItemYezizhiice = new ItemDrink(3, 9F, "ItemYezizhiice",0);
        ItemXiangjiaozhiice = new ItemDrink(3, 9F, "ItemXiangjiaozhiice",0);
        ItemHongjiu = new ItemWine(3, 8F, "ItemHongjiu").setAlwaysEdible();
        ItemBaijiu = new ItemWine(3, 8F, "ItemBaijiu").setAlwaysEdible();
        ItemPingguojiu = new ItemWine(3, 8F, "ItemPingguojiu").setAlwaysEdible();
        ItemPutaojiu = new ItemWine(3, 8F, "ItemPutaojiu").setAlwaysEdible();
        ItemLizijiu = new ItemWine(3, 8F, "ItemLizijiu").setAlwaysEdible();
        ItemLizhijiu = new ItemWine(3, 8F, "ItemLizhijiu").setAlwaysEdible();
        ItemTaozijiu = new ItemWine(3, 8F, "ItemTaozijiu").setAlwaysEdible();
        ItemMangguojiu = new ItemWine(3, 8F, "ItemMangguojiu").setAlwaysEdible();
        ItemNingmengjiu = new ItemWine(3, 8F, "ItemNingmengjiu").setAlwaysEdible();
        ItemShiliujiu = new ItemWine(3, 8F, "ItemShiliujiu").setAlwaysEdible();
        ItemJinputaojiu = new ItemGoldenGrapeWine(3, 20F, "ItemJinputaojiu").setAlwaysEdible();
        ItemJinpingguojiu = new ItemGoldenAppleWine(3, 20F, "ItemJinpingguojiu").setAlwaysEdible();
        ItemGuojiang = new ItemJam();
        ItemBinggan = new ItemCookie(3, 10F, "ItemBinggan");
        ItemDangao = new ItemCakeFoodcraft();
        ItemCong = new ItemReed(FoodcraftPlants.BlockCong).setUnlocalizedName("ItemCong").setCreativeTab(FoodCraft.FcTabPlant);
        MinecraftForge.addGrassSeed(new ItemStack(ItemCong), 2);
        ItemLajiao = new ItemFoodChili();
        ItemCaidao = new Item().setUnlocalizedName("ItemCaidao").setCreativeTab(FoodCraft.FcTabMachine).setMaxDamage(59).setMaxStackSize(1);
        ItemCaidaoHJ = new ItemKitchenKnifeGold();
        ItemCaidaoZS = new ItemKitchenKnifeDiamond();
        ItemCaidaoLBS = new ItemKitchenKnifeEmerald();
        ItemJinghuashuitong = new ItemCleaningBucket(EnumHelper.addToolMaterial("JHST", 0, 16, 2.0F, 0.0F, 15));
        ItemWrench = new ItemWrench("ItemWrench");
        ItemTest = new ItemTest();

        /**------------------------------ Machines and Tools  ------------------------------*/
        GameRegistry.registerItem(ItemTiepian, "ItemTiepian");
        GameRegistry.registerItem(ItemJinghuashuitong, "ItemJinghuashuitong");
        GameRegistry.registerItem(ItemDianluban, "ItemDianluban");
        GameRegistry.registerItem(ItemCaidao, "ItemCaidao");
        GameRegistry.registerItem(ItemCaidaoHJ, "ItemCaidaoHJ");
        GameRegistry.registerItem(ItemCaidaoZS, "ItemCaidaoZS");
        GameRegistry.registerItem(ItemCaidaoLBS, "ItemCaidaoLBS");
        GameRegistry.registerItem(ItemWrench, "ItemWrench");
        GameRegistry.registerItem(ItemJinkela, "ItemJinkela");
        GameRegistry.registerItem(ItemNull, "ItemNull");
        /**------------------------------ Plants  ------------------------------*/
        GameRegistry.registerItem(ItemDami, "ItemDami");
        GameRegistry.registerItem(ItemHuashen, "ItemHuashen");
        GameRegistry.registerItem(ItemDouzi, "ItemDouzi");
        GameRegistry.registerItem(ItemNuomi, "ItemNuomi");
        GameRegistry.registerItem(ItemHongdou, "ItemHongdou");
        GameRegistry.registerItem(ItemLvdou, "ItemLvdou");
        GameRegistry.registerItem(ItemBailuobo, "ItemBailuobo");
        GameRegistry.registerItem(ItemShucai, "ItemShucai");
        GameRegistry.registerItem(ItemLajiao, "ItemLajiao");
        GameRegistry.registerItem(ItemQingjiao, "ItemQingjiao");
        GameRegistry.registerItem(ItemFanqie, "ItemFanqie");
        GameRegistry.registerItem(ItemQiezi, "ItemQiezi");
        GameRegistry.registerItem(ItemCong, "ItemCong");
        GameRegistry.registerItem(ItemDoujiao, "ItemDoujiao");
        GameRegistry.registerItem(ItemHuanggua, "ItemHuanggua");
        GameRegistry.registerItem(ItemYumi, "ItemYumi");
        GameRegistry.registerItem(ItemHongshu, "ItemHongshu");
        GameRegistry.registerItem(ItemZongye, "ItemZongye");
        GameRegistry.registerItem(ItemPutao, "ItemPutao");
        GameRegistry.registerItem(ItemJinputao, "ItemJinputao");
        GameRegistry.registerItem(ItemLi, "ItemLi");
        GameRegistry.registerItem(ItemLizhi, "ItemLizhi");
        GameRegistry.registerItem(ItemTaozi, "ItemTaozi");
        GameRegistry.registerItem(ItemJuzi, "ItemJuzi");
        GameRegistry.registerItem(ItemPipa, "ItemPipa");
        GameRegistry.registerItem(ItemMangguo, "ItemMangguo");
        GameRegistry.registerItem(ItemNingmeng, "ItemNingmeng");
        GameRegistry.registerItem(ItemYouzi, "ItemYouzi");
        GameRegistry.registerItem(ItemShizi, "ItemShizi");
        GameRegistry.registerItem(ItemMugua, "ItemMugua");
        GameRegistry.registerItem(ItemShanzha, "ItemShanzha");
        GameRegistry.registerItem(ItemLongyan, "ItemLongyan");
        GameRegistry.registerItem(ItemShiliu, "ItemShiliu");
        GameRegistry.registerItem(ItemHongzao, "ItemHongzao");
        GameRegistry.registerItem(ItemCaomei, "ItemCaomei");
        GameRegistry.registerItem(ItemYezi, "ItemYezi");
        GameRegistry.registerItem(ItemYingtao, "ItemYingtao");
        GameRegistry.registerItem(ItemXiangjiao, "ItemXiangjiao");
        GameRegistry.registerItem(ItemShucaizhong, "ItemShucaizhong");
        GameRegistry.registerItem(ItemLajiaozhong, "ItemLajiaozhong");
        GameRegistry.registerItem(ItemFanqiezhong, "ItemFanqiezhong");
        GameRegistry.registerItem(ItemPutaozhong, "ItemPutaozhong");
        GameRegistry.registerItem(ItemQiezizhong, "ItemQiezizhong");
        GameRegistry.registerItem(ItemQingjiaozhong, "ItemQingjiaozhong");
        GameRegistry.registerItem(ItemYumizhong, "ItemYumizhong");
        GameRegistry.registerItem(ItemHuangguazhong, "ItemHuangguazhong");
        /**------------------------------  Drinks  ------------------------------*/
        GameRegistry.registerItem(ItemDoujiang, "ItemDoujiang");
        GameRegistry.registerItem(ItemHongjiu, "ItemHongjiu");
        GameRegistry.registerItem(ItemBaijiu, "ItemBaijiu");
        GameRegistry.registerItem(ItemPutaojiu, "ItemPutaojiu");
        GameRegistry.registerItem(ItemPingguojiu, "ItemPingguojiu");
        GameRegistry.registerItem(ItemJinputaojiu, "ItemJinputaojiu");
        GameRegistry.registerItem(ItemJinpingguojiu, "ItemJinpingguojiu");
        GameRegistry.registerItem(ItemLizijiu, "ItemLizijiu");
        GameRegistry.registerItem(ItemLizhijiu, "ItemLizhijiu");
        GameRegistry.registerItem(ItemTaozijiu, "ItemTaozijiu");
        GameRegistry.registerItem(ItemMangguojiu, "ItemMangguojiu");
        GameRegistry.registerItem(ItemNingmengjiu, "ItemNingmengjiu");
        GameRegistry.registerItem(ItemShiliujiu, "ItemShiliujiu");
        GameRegistry.registerItem(ItemQiaokelishui, "ItemQiaokelishui");
        GameRegistry.registerItem(ItemHuluobozhi, "ItemHuluobozhi");
        GameRegistry.registerItem(ItemCha, "ItemCha");
        GameRegistry.registerItem(ItemPutaozhi, "ItemPutaozhi");
        GameRegistry.registerItem(ItemPingguozhi, "ItemPingguozhi");
        GameRegistry.registerItem(ItemShucaizhi, "ItemShucaizhi");
        GameRegistry.registerItem(ItemXiguazhi, "ItemXiguazhi");
        GameRegistry.registerItem(ItemJinputaozhi, "ItemJinputaozhi");
        GameRegistry.registerItem(ItemJinpingguozhi, "ItemJinpingguozhi");
        GameRegistry.registerItem(ItemKele, "ItemKele");
        GameRegistry.registerItem(ItemXuebi, "ItemXuebi");
        GameRegistry.registerItem(ItemNaicha, "ItemNaicha");
        GameRegistry.registerItem(ItemKafei, "ItemKafei");
        GameRegistry.registerItem(ItemQiaokelinai, "ItemQiaokelinai");
        GameRegistry.registerItem(ItemDounai, "ItemDounai");
        GameRegistry.registerItem(ItemBailuobozhi, "ItemBailuobozhi");
        GameRegistry.registerItem(ItemFanqiezhi, "ItemFanqiezhi");
        GameRegistry.registerItem(ItemYumizhi, "ItemYumizhi");
        GameRegistry.registerItem(ItemHuangguazhi, "ItemHuangguazhi");
        GameRegistry.registerItem(ItemLizizhi, "ItemLizizhi");
        GameRegistry.registerItem(ItemLizhizhi, "ItemLizhizhi");
        GameRegistry.registerItem(ItemTaozizhi, "ItemTaozizhi");
        GameRegistry.registerItem(ItemJuzizhi, "ItemJuzizhi");
        GameRegistry.registerItem(ItemPipazhi, "ItemPipazhi");
        GameRegistry.registerItem(ItemMangguozhi, "ItemMangguozhi");
        GameRegistry.registerItem(ItemNingmengzhi, "ItemNingmengzhi");
        GameRegistry.registerItem(ItemYouzizhi, "ItemYouzizhi");
        GameRegistry.registerItem(ItemShizizhi, "ItemShizizhi");
        GameRegistry.registerItem(ItemMuguazhi, "ItemMuguazhi");
        GameRegistry.registerItem(ItemShanzhazhi, "ItemShanzhazhi");
        GameRegistry.registerItem(ItemShiliuzhi, "ItemShiliuzhi");
        GameRegistry.registerItem(ItemHongzaozhi, "ItemHongzaozhi");
        GameRegistry.registerItem(ItemCaomeizhi, "ItemCaomeizhi");
        GameRegistry.registerItem(ItemYezizhi, "ItemYezizhi");
        GameRegistry.registerItem(ItemYingtaozhi, "ItemYingtaozhi");
        GameRegistry.registerItem(ItemXiangjiaozhi, "ItemXiangjiaozhi");
        GameRegistry.registerItem(ItemYenai, "ItemYenai");
        GameRegistry.registerItem(ItemQiaokelinaiice, "ItemQiaokelinaiice");
        GameRegistry.registerItem(ItemPutaozhiice, "ItemPutaozhiice");
        GameRegistry.registerItem(ItemPingguozhiice, "ItemPingguozhiice");
        GameRegistry.registerItem(ItemJinputaozhiice, "ItemJinputaozhiice");
        GameRegistry.registerItem(ItemXiguazhiice, "ItemXiguazhiice");
        GameRegistry.registerItem(ItemJinpingguozhiice, "ItemJinpingguozhiice");
        GameRegistry.registerItem(ItemLizhizhiice, "ItemLizhizhiice");
        GameRegistry.registerItem(ItemTaozizhiice, "ItemTaozizhiice");
        GameRegistry.registerItem(ItemJuzizhiice, "ItemJuzizhiice");
        GameRegistry.registerItem(ItemMangguozhiice, "ItemMangguozhiice");
        GameRegistry.registerItem(ItemNingmengzhiice, "ItemNingmengzhiice");
        GameRegistry.registerItem(ItemMuguazhiice, "ItemMuguazhiice");
        GameRegistry.registerItem(ItemCaomeizhiice, "ItemCaomeizhiice");
        GameRegistry.registerItem(ItemYezizhiice, "ItemYezizhiice");
        GameRegistry.registerItem(ItemXiangjiaozhiice, "ItemXiangjiaozhiice");
        /**------------------------------  Staple Food  ------------------------------*/
        GameRegistry.registerItem(ItemMogudunjitang, "ItemMogudunjitang");
        GameRegistry.registerItem(ItemDangeng, "ItemDangeng");
        GameRegistry.registerItem(ItemMian, "ItemMian");
        GameRegistry.registerItem(ItemGuoqiaomixian, "ItemGuoqiaomixian");
        GameRegistry.registerItem(ItemPidanshourouzhou, "ItemPidanshourouzhou");
        GameRegistry.registerItem(ItemLabazhou, "ItemLabazhou");
        GameRegistry.registerItem(ItemFanqiechaojidanfan, "ItemFanqiechaojidanfan");
        GameRegistry.registerItem(ItemDisanxian, "ItemDisanxian");
        GameRegistry.registerItem(ItemYuxiangrousi, "ItemYuxiangrousi");
        GameRegistry.registerItem(ItemGongbaojiding, "ItemGongbaojiding");
        GameRegistry.registerItem(ItemChaotudousifan, "ItemChaotudousifan");
        GameRegistry.registerItem(ItemDuojiaoyutou, "ItemDuojiaoyutou");
        GameRegistry.registerItem(ItemMapodoufufan, "ItemMapodoufufan");
        GameRegistry.registerItem(ItemHongshaoroufan, "ItemHongshaoroufan");
        GameRegistry.registerItem(ItemHuiguoroufan, "ItemHuiguoroufan");
        GameRegistry.registerItem(ItemAeljichifan, "ItemAeljichifan");
        GameRegistry.registerItem(ItemLaziji, "ItemLaziji");
        GameRegistry.registerItem(ItemKoushuiji, "ItemKoushuiji");
        GameRegistry.registerItem(ItemBaiqiuji, "ItemBaiqiuji");
        GameRegistry.registerItem(ItemCongyouji, "ItemCongyouji");
        GameRegistry.registerItem(ItemSuancaiyu, "ItemSuancaiyu");
        GameRegistry.registerItem(ItemMalayu, "ItemMalayu");
        GameRegistry.registerItem(ItemQingzhenyu, "ItemQingzhenyu");
        GameRegistry.registerItem(ItemKelejichifan, "ItemKelejichifan");
        GameRegistry.registerItem(ItemGalijiroufan, "ItemGalijiroufan");
        GameRegistry.registerItem(ItemShuizhuniurou, "ItemShuizhuniurou");
        GameRegistry.registerItem(ItemYifen, "ItemYifen");
        GameRegistry.registerItem(ItemYifenpork, "ItemYifenpork");
        GameRegistry.registerItem(ItemYifenbeef, "ItemYifenbeef");
        GameRegistry.registerItem(ItemYifenchicken, "ItemYifenchicken");
        GameRegistry.registerItem(ItemRibendoufu, "ItemRibendoufu");
        GameRegistry.registerItem(ItemChangfen, "ItemChangfen");
        /**------------------------------  Ingredients    ------------------------------*/
        GameRegistry.registerItem(Itemwater, "Itemwater");
        GameRegistry.registerItem(Itemfan, "Itemfan");
        GameRegistry.registerItem(ItemMianfen, "ItemMianfen");
        GameRegistry.registerItem(ItemYan, "ItemYan");
        GameRegistry.registerItem(ItemMianpi, "ItemMianpi");
        GameRegistry.registerItem(ItemDouban, "ItemDouban");
        GameRegistry.registerItem(ItemQiaokelifen, "ItemQiaokelifen");
        GameRegistry.registerItem(ItemJiaozixian, "ItemJiaozixian");
        GameRegistry.registerItem(ItemHuashenyou, "ItemHuashenyou");
        GameRegistry.registerItem(ItemBaifan, "ItemBaifan");
        GameRegistry.registerItem(ItemJitui, "ItemJitui");
        GameRegistry.registerItem(ItemJichi, "ItemJichi");
        GameRegistry.registerItem(ItemDajirou, "ItemDajirou");
        GameRegistry.registerItem(ItemZhongjirou, "ItemZhongjirou");
        GameRegistry.registerItem(ItemXiaojirou, "ItemXiaojirou");
        GameRegistry.registerItem(ItemTudoupian, "ItemTudoupian");
        GameRegistry.registerItem(ItemTudousi, "ItemTudousi");
        GameRegistry.registerItem(ItemJiangyou, "ItemJiangyou");
        GameRegistry.registerItem(ItemCu, "ItemCu");
        GameRegistry.registerItem(ItemDousha, "ItemDousha");
        GameRegistry.registerItem(ItemDianfen, "ItemDianfen");
        GameRegistry.registerItem(ItemNuomifen, "ItemNuomifen");
        GameRegistry.registerItem(ItemNuomituan, "ItemNuomituan");
        GameRegistry.registerItem(ItemHuashentangyuanxian, "ItemHuashentangyuanxian");
        GameRegistry.registerItem(ItemDoufusi, "ItemDoufusi");
        GameRegistry.registerItem(ItemLuobosi, "ItemLuobosi");
        GameRegistry.registerItem(ItemBailuobosi, "ItemBailuobosi");
        GameRegistry.registerItem(ItemMianfensi, "ItemMianfensi");
        GameRegistry.registerItem(ItemGalikuai, "ItemGalikuai");
        GameRegistry.registerItem(ItemLaweixunliao, "ItemLaweixunliao");
        GameRegistry.registerItem(ItemGuojiang, "ItemGuojiang");
        GameRegistry.registerItem(ItemShaojiaodeshiwu, "ItemShaojiaodeshiwu");
        /**------------------------------  Snacks   ------------------------------*/
        GameRegistry.registerItem(ItemYouyurou, "ItemYouyurou");
        GameRegistry.registerItem(ItemShuyouyurou, "ItemShuyouyurou");
        GameRegistry.registerItem(ItemYouyusi, "ItemYouyusi");
        GameRegistry.registerItem(ItemJianjidan, "ItemJianjidan");
        GameRegistry.registerItem(ItemLaobing, "ItemLaobing");
        GameRegistry.registerItem(ItemJiaozi, "ItemJiaozi");
        GameRegistry.registerItem(ItemJianjiao, "ItemJianJiao");
        GameRegistry.registerItem(ItemDoufu, "ItemDoufu");
        GameRegistry.registerItem(ItemDoufugan, "ItemDoufugan");
        GameRegistry.registerItem(ItemChaotudoupian, "ItemChaotudoupian");
        GameRegistry.registerItem(ItemXifan, "ItemXifan");
        GameRegistry.registerItem(ItemZongzi, "ItemZongzi");
        GameRegistry.registerItem(ItemYuebing, "ItemYuebing");
        GameRegistry.registerItem(ItemTangyuan, "ItemTangyuan");
        GameRegistry.registerItem(ItemMahua, "ItemMahua");
        GameRegistry.registerItem(ItemChunjuan, "ItemChunjuan");
        GameRegistry.registerItem(ItemShupian, "ItemShupian");
        GameRegistry.registerItem(ItemXiangchang, "ItemXiangchang");
        GameRegistry.registerItem(ItemLachang, "ItemLachang");
        GameRegistry.registerItem(ItemLarou, "ItemLarou");
        GameRegistry.registerItem(ItemZhaxiangchang, "ItemZhaxiangchang");
        GameRegistry.registerItem(ItemPisa, "ItemPisa");
        GameRegistry.registerItem(ItemHanbaobao, "ItemHanbaobao");
        GameRegistry.registerItem(ItemYoutiao, "ItemYoutiao");
        GameRegistry.registerItem(ItemLatiao, "ItemLatiao");
        GameRegistry.registerItem(ItemJikuai, "ItemJikuai");
        GameRegistry.registerItem(ItemYuanweijikuai, "ItemYuanweijikuai");
        GameRegistry.registerItem(ItemShutiao, "ItemShutiao");
        GameRegistry.registerItem(ItemJimihua, "ItemJimihua");
        GameRegistry.registerItem(ItemAeljichi, "ItemAeljichi");
        GameRegistry.registerItem(ItemZhadoufu, "ItemZhadoufu");
        GameRegistry.registerItem(ItemZhachunjuan, "ItemZhachunjuan");
        GameRegistry.registerItem(ItemZhamahua, "ItemZhamahua");
        GameRegistry.registerItem(ItemZhajitui, "ItemZhajitui");
        GameRegistry.registerItem(ItemKaohongshu, "ItemKaohongshu");
        GameRegistry.registerItem(ItemKaoyumi, "ItemKaoyumi");
        GameRegistry.registerItem(ItemBaoyumihua, "ItemBaoyumihua");
        /**------------------------------  Snacks    ------------------------------*/
        GameRegistry.registerItem(ItemQiaokeli, "ItemQiaokeli");
        GameRegistry.registerItem(ItemNiangao, "ItemNiangao");
        GameRegistry.registerItem(ItemHetaosu, "ItemHetaosu");
        GameRegistry.registerItem(ItemAici, "ItemAici");
        GameRegistry.registerItem(ItemCiba, "ItemCiba");
        GameRegistry.registerItem(ItemNainao, "ItemNainao");
        GameRegistry.registerItem(ItemMantou, "ItemMantou");
        GameRegistry.registerItem(ItemSuancaibing, "ItemSuancaibing");
        GameRegistry.registerItem(ItemZhaniangao, "ItemZhaniangao");
        GameRegistry.registerItem(ItemZhamianbao, "ItemZhamianbao");
        GameRegistry.registerItem(ItemRegou, "ItemRegou");
        GameRegistry.registerItem(ItemBingganXN, "ItemBingganXN");
        GameRegistry.registerItem(ItemBingganF, "ItemBingganF");
        GameRegistry.registerItem(ItemBinggan, "ItemBinggan");
        GameRegistry.registerItem(ItemDangao, "ItemDangao");
        /**------------------------------------------------------------------------*/
    }
}