package com.foodcraft.init;

import com.foodcraft.plant.blocks.BlockBannana;
import com.foodcraft.plant.blocks.BlockCoconut;
import com.foodcraft.plant.blocks.BlockFoodcraftCrops;
import com.foodcraft.plant.blocks.BlockFruit;
import com.foodcraft.plant.blocks.BlockScallion;
import com.foodcraft.plant.blocks.BlockTree;
import com.foodcraft.plant.blocks.TreeBannana;
import com.foodcraft.plant.blocks.TreeCoconut;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class FoodcraftPlants {
	
	public static Block FCleaves;
	public static Block BlockLishu,BlockLi;
	public static Block BlockLizhishu,BlockLizhi;
	public static Block BlockTaozishu,BlockTaozi;
	public static Block BlockJuzishu,BlockJuzi;
	public static Block BlockPipashu,BlockPipa;
	public static Block BlockMangguoshu,BlockMangguo;
	public static Block BlockNingmengshu,BlockNingmeng;
	public static Block BlockYouzishu,BlockYouzi;
	public static Block BlockShizishu,BlockShizi;
	public static Block BlockMuguashu,BlockMugua;
	public static Block BlockShanzhashu,BlockShanzha;
	public static Block BlockLongyanshu,BlockLongyan;
	public static Block BlockShiliushu,BlockShiliu;
	public static Block BlockHongzaoshu,BlockHongzao;
	public static Block BlockYezishu,BlockYezi;	
	public static Block BlockYingtaoshu,BlockYingtao;
	public static Block BlockXiangjiaoshu,BlockXiangjiao;
	public static Block BlockShuidao,BlockDouzi,BlockHuashen,BlockShucai,BlockFanqie,BlockLajiao,BlockPutao,BlockQiezi,BlockCong,BlockQingjiao,BlockHongdou,BlockLvdou,
	BlockHongshu,BlockBailuobo,BlockYumi,BlockHuanggua,BlockCaomei,BlockNuodao;
	
	public static void init() {	
	FCleaves = new BlockFruit("FCleaves","sapling");
	BlockLi = new BlockFruit("BlockLi","foodcraft:ItemLi");
	BlockLizhi = new BlockFruit("BlockLizhi","foodcraft:ItemLizhi");
	BlockTaozi = new BlockFruit("BlockTaozi","foodcraft:ItemTaozi");
	BlockJuzi = new BlockFruit("BlockJuzi","foodcraft:ItemJuzi");
	BlockPipa = new BlockFruit("BlockPipa","foodcraft:ItemPipa");
	BlockMangguo = new BlockFruit("BlockMangguo","foodcraft:ItemMangguo");
	BlockNingmeng = new BlockFruit("BlockNingmeng","foodcraft:ItemNingmeng");
	BlockYouzi = new BlockFruit("BlockYouzi","foodcraft:ItemYouzi");
	BlockShizi = new BlockFruit("BlockShizi","foodcraft:ItemShizi");
	BlockMugua = new BlockFruit("BlockMugua","foodcraft:ItemMugua");
	BlockShanzha = new BlockFruit("BlockShanzha","foodcraft:ItemShanzha");
	BlockLongyan = new BlockFruit("BlockLongyan","foodcraft:ItemLongyan");
	BlockShiliu = new BlockFruit("BlockShiliu","foodcraft:ItemShiliu");
	BlockHongzao = new BlockFruit("BlockHongzao","foodcraft:ItemHongzao");
	BlockYingtao = new BlockFruit("BlockYingtao","foodcraft:ItemYingtao");
	BlockXiangjiao = new BlockBannana("BlockXiangjiao","foodcraft:ItemXiangjiao");
	BlockYezi = new BlockCoconut("BlockYezi","foodcraft:ItemYezi");
	BlockCong = new BlockScallion();		
	BlockLishu = new BlockTree(BlockLi,"BlockLishu");	
	BlockLizhishu = new BlockTree(BlockLizhi,"BlockLizhishu");
	BlockTaozishu = new BlockTree(BlockTaozi,"BlockTaozishu");
	BlockJuzishu = new BlockTree(BlockJuzi,"BlockJuzishu");
	BlockPipashu = new BlockTree(BlockPipa, "BlockPipashu");
	BlockMangguoshu = new BlockTree(BlockMangguo,"BlockMangguoshu");
	BlockNingmengshu = new BlockTree(BlockNingmeng,"BlockNingmengshu");
	BlockYouzishu = new BlockTree(BlockYouzi, "BlockYouzishu");
	BlockShizishu = new BlockTree(BlockShizi, "BlockShizishu");
	BlockMuguashu = new BlockTree(BlockMugua, "BlockMuguashu");
	BlockShanzhashu = new BlockTree(BlockShanzha, "BlockShanzhashu");
	BlockLongyanshu = new BlockTree(BlockLongyan, "BlockLongyanshu");
	BlockShiliushu = new BlockTree(BlockShiliu, "BlockShiliushu");
	BlockHongzaoshu = new BlockTree(BlockHongzao, "BlockHongzaoshu");
	BlockYezishu = new TreeCoconut(BlockYezi);
	BlockYingtaoshu = new BlockTree(BlockYingtao, "BlockYingtaoshu");
	BlockXiangjiaoshu = new TreeBannana(BlockXiangjiao);
	BlockQingjiao = new BlockFoodcraftCrops("foodcraft:ItemQingjiaozhong","foodcraft:ItemQingjiao","BlockQingjiao");
	BlockHongdou = new BlockFoodcraftCrops("foodcraft:ItemHongdou","foodcraft:ItemHongdou","BlockHongdou");
	BlockHongshu = new BlockFoodcraftCrops("foodcraft:ItemHongshu","foodcraft:ItemHongshu","BlockHongshu");
	BlockLvdou = new BlockFoodcraftCrops("foodcraft:ItemLvdou","foodcraft:ItemLvdou","BlockLvdou");
	BlockBailuobo = new BlockFoodcraftCrops("foodcraft:ItemBailuobo","foodcraft:ItemBailuobo","BlockBailuobo");
	BlockYumi = new BlockFoodcraftCrops("foodcraft:ItemYumizhong","foodcraft:ItemYumi","BlockYumi");
	BlockHuanggua = new BlockFoodcraftCrops("foodcraft:ItemHuangguazhong","foodcraft:ItemHuanggua","BlockHuanggua");
	BlockCaomei = new BlockFoodcraftCrops("foodcraft:ItemCaomei","foodcraft:ItemCaomei","BlockCaomei");
	BlockNuodao = new BlockFoodcraftCrops("foodcraft:ItemStickyRice","foodcraft:ItemStickyRice","BlockNuodao");
	BlockShuidao = new BlockFoodcraftCrops("foodcraft:ItemRice","foodcraft:ItemRice","BlockShuidao");
	BlockDouzi = new BlockFoodcraftCrops("foodcraft:ItemBeans","foodcraft:ItemBeans","BlockDouzi");
	BlockHuashen = new BlockFoodcraftCrops("foodcraft:ItemPeanut","foodcraft:ItemPeanut","BlockHuashen");
	BlockShucai = new BlockFoodcraftCrops("foodcraft:ItemShucaizhong","foodcraft:ItemVegetable","BlockShucai");
	BlockLajiao = new BlockFoodcraftCrops("foodcraft:ItemLajiaozhong","foodcraft:ItemChili","BlockLajiao");
	BlockFanqie = new BlockFoodcraftCrops("foodcraft:ItemFanqiezhong","foodcraft:ItemTomato","BlockFanqie");
	BlockQiezi = new BlockFoodcraftCrops("foodcraft:ItemQiezizhong","foodcraft:ItemEggplant","BlockQiezi");
	BlockPutao = new BlockFoodcraftCrops("foodcraft:ItemPutaozhong","foodcraft:ItemGrapes","BlockPutao");
	
	GameRegistry.registerBlock(FCleaves,"FCleaves");
	GameRegistry.registerBlock(BlockLishu,"BlockLishu");
	GameRegistry.registerBlock(BlockLi,"BlockLi");
	GameRegistry.registerBlock(BlockLizhishu,"BlockLizhishu");
	GameRegistry.registerBlock(BlockLizhi,"BlockLizhi");
	GameRegistry.registerBlock(BlockTaozishu,"BlockTaozishu");
	GameRegistry.registerBlock(BlockTaozi,"BlockTaozi");
	GameRegistry.registerBlock(BlockJuzishu,"BlockJuzishu");
	GameRegistry.registerBlock(BlockJuzi,"BlockJuzi");
	GameRegistry.registerBlock(BlockPipashu,"BlockPipashu");
	GameRegistry.registerBlock(BlockPipa,"BlockPipa");
	GameRegistry.registerBlock(BlockMangguoshu,"BlockMangguoshu");
	GameRegistry.registerBlock(BlockMangguo,"BlockMangguo");
	GameRegistry.registerBlock(BlockNingmengshu,"BlockNingmengshu");
	GameRegistry.registerBlock(BlockNingmeng,"BlockNingmeng");	
	GameRegistry.registerBlock(BlockYouzishu,"BlockYouzishu");
	GameRegistry.registerBlock(BlockYouzi,"BlockYouzi");	
	GameRegistry.registerBlock(BlockShizishu,"BlockShizishu");
	GameRegistry.registerBlock(BlockShizi,"BlockShizi");	
	GameRegistry.registerBlock(BlockMuguashu,"BlockMuguashu");
	GameRegistry.registerBlock(BlockMugua,"BlockMugua");	
	GameRegistry.registerBlock(BlockShanzhashu,"BlockShanzhashu");
	GameRegistry.registerBlock(BlockShanzha,"BlockShanzha");	
	GameRegistry.registerBlock(BlockLongyanshu,"BlockLongyanshu");
	GameRegistry.registerBlock(BlockLongyan,"BlockLongyan");	
	GameRegistry.registerBlock(BlockShiliushu,"BlockShiliushu");
	GameRegistry.registerBlock(BlockShiliu,"BlockShiliu");
	GameRegistry.registerBlock(BlockHongzaoshu,"BlockHongzaoshu");
	GameRegistry.registerBlock(BlockHongzao,"BlockHongzao");
	GameRegistry.registerBlock(BlockYezishu,"BlockYezishu");
	GameRegistry.registerBlock(BlockYezi,"BlockYezi");
	GameRegistry.registerBlock(BlockYingtaoshu,"BlockYingtaoshu");
	GameRegistry.registerBlock(BlockYingtao,"BlockYingtao");
	GameRegistry.registerBlock(BlockXiangjiaoshu,"BlockXiangjiaoshu");
	GameRegistry.registerBlock(BlockXiangjiao,"BlockXiangjiao");
	GameRegistry.registerBlock(BlockDouzi,"BlockDouzi");
	GameRegistry.registerBlock(BlockShuidao,"BlockShuidao");
	GameRegistry.registerBlock(BlockHuashen,"BlockHuashen");
	GameRegistry.registerBlock(BlockFanqie,"BlockFanqie");
	GameRegistry.registerBlock(BlockLajiao,"BlockLajiao");
	GameRegistry.registerBlock(BlockShucai,"BlockShucai");
	GameRegistry.registerBlock(BlockPutao,"BlockPutao");
	GameRegistry.registerBlock(BlockQiezi,"BlockQiezi");
	GameRegistry.registerBlock(BlockQingjiao,"BlockQingjiao");
	GameRegistry.registerBlock(BlockHongdou,"BlockHongdou");
	GameRegistry.registerBlock(BlockLvdou,"BlockLvdou");
	GameRegistry.registerBlock(BlockHongshu,"BlockHongshu");
	GameRegistry.registerBlock(BlockBailuobo,"BlockBailuobo");
	GameRegistry.registerBlock(BlockYumi,"BlockYumi");
	GameRegistry.registerBlock(BlockHuanggua,"BlockHuanggua");
	GameRegistry.registerBlock(BlockCaomei,"BlockCaomei");
	GameRegistry.registerBlock(BlockNuodao,"BlockNuodao");
	GameRegistry.registerBlock(BlockCong,"BlockCong");	
	}
}
